# Creative Data Visualization {.unnumbered }

## Objectives {.unnumbered}

The objective of this assignment is to use your skills in ***R*** to aid in producing a creative-nontraditional-artistic (or choose your own similar adjective!) **data visualization** using either a dataset you find or, ideally, some of your own data! This is your chance to both showcase your ***R*** coding and data wrangling skills **and** explore your creative side.

> **NOTE**: We are using the term "visualization" here to mean something more general than that term would usually imply... i.e., your "visualization" could be in a sensory modality OTHER than sight. For example, you might imagine creating an auditory or olfactory or tactile representation of data.

Your visualization does not have to be sophisticated, but it must involve, in some sense, loading, transforming, and visualizing a set of custom data -- either a publicly-available dataset or data relevant to your own work or your field of study -- into some kind of interesting, creative representation. Mostly, I am looking for you try think **outside the box** and be experimental or nontraditional in how you represent data... to that end, it would be okay if you simply want to present a cool algorithm/protocol/description about how you would like to transform your data even if you are not able to implement it.

Check out [this website](http://www.dnasonification.org/) for an example of the kind of thing I am thinking of...

> DNA Sonification refers to the use of audio to convey the information content of a DNA sequence. Audio is created using the rules of gene expression and codons are played as musical notes.

> Temple, Mark D. 2017. An auditory display tool for DNA sequence analysis.” *BMC Bioinformatics* 18: 221. https://doi.org/10.1186/s12859-017-1632-x.

## What to Turn In {.unnumbered}

If you can do your visualization entirely with code, then start a new ***R*** project in a new ***GitHub*** repository using one of the methods outlined in [**Module 06**](module-06). You should call it "creative-data-visualization". 

By the due date for this assignment, you should post to your code (if you are doing this with code) along with the dataset you are visualizing to this ***GitHub*** repository and submit the URL into the assignment submission text field.

If your visualization cannot be done entirely with code (i.e., if you produce "something else" with your data after wrangling/transforming with code -- a recording, painting, physical object, text or graphic representation of a process/algorithm for visualization that you cannot yet implement), please follow the same instructions above, but then also take a photo/video/recording of your finished product or a sketch of your (unrealized) ideas and include it in your rendered ".qmd" file.

> **NOTE:** We should be able to CLONE whatever is in your repository and render your associated ".qmd" file to show all of the work for this creative data visualization.
