{
  "hash": "3210e11da810f2e8d4a2d1368eb14bc4",
  "result": {
    "engine": "knitr",
    "markdown": "# Categorical Data Analysis {#module-20}\n\n## Objectives\n\n> In this module, we examine how simple linear regression can be applied to datasets where our predictor variable is discrete or categorical rather than continuous. Indeed, we will see that One-Way (and Two-Way) Analysis of Variance (ANOVA) is a specific application of simple (and multiple) linear regression. We also look at other methods for basic statistical analysis of categorical data.\n\n## Preliminaries\n\n- Install these packages in ***R***:\n[{dunn.test}](https://cran.r-project.org/web/packages/dunn.test/dunn.test.pdf), [{conover.test}](https://cran.r-project.org/web/packages/conover.test/conover.test.pdf),\n[{datawizard}](https://cran.r-project.org/web/packages/datawizard/datawizard.pdf),\n[{sjPlot}](https://cran.r-project.org/web/packages/sjPlot/sjPlot.pdf),\n[{emmeans}](https://cran.r-project.org/web/packages/emmeans/emmeans.pdf), and [{permuco}](https://cran.r-project.org/web/packages/permuco/permuco.pdf)\n- Install and load this package in ***R***:\n[{effectsize}](https://cran.r-project.org/web/packages/effectsize/effectsize.pdf)\n- Load {tidyverse}, {broom}, and {infer}\n\n\n\n\n\n## Categorical Predictors\n\nThus far we have used simple linear regression models involving continuous explanatory variables, but we can also use a discrete or categorical explanatory variable, made up of 2 or more groups that are coded as \"factors\" (i.e., we use integer values from 1 to $k$ discrete groups as dummy values for our categorical variables). Let's load in our zombie apocalpyse survivor data again, but this time after doing so, we will convert **gender** and **major** to factors using the function `as.factor()`. [We could also do this by reading the data in using `read.csv()`, which has as a default argument `stringsAsFactors=TRUE`.] Then look at the `class()` and `summary()` of the variable **gender**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf <- \"https://raw.githubusercontent.com/difiore/ada-datasets/main/zombies.csv\"\nz <- read_csv(f, col_names = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n## Rows: 1000 Columns: 10\n## ── Column specification ────────────────────────────────────────────────────────\n## Delimiter: \",\"\n## chr (4): first_name, last_name, gender, major\n## dbl (6): id, height, weight, zombies_killed, years_of_education, age\n## \n## ℹ Use `spec()` to retrieve the full column specification for this data.\n## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nz$gender <- factor(z$gender) # can also use `as.factor()`\nz$major <- factor(z$major) # can also use `as.factor()`\n\nclass(z$gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] \"factor\"\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(z$gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Female   Male \n##    494    506\n```\n\n\n:::\n:::\n\n\nAs with our prior simple regression analysis, we want to evaluate the effect of a predictor variable on a response variable (e.g., **height**), but this time we want our predictor to be a discrete, or categorical, variable (e.g., **gender**) rather than a continuous one. We can start off by plotting **height** by **gender** using the same formula notation we have been using.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(z$height ~ z$gender)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n# or, with {ggplot}\nggplot(data = z, aes(x = gender, y = height)) +\n  geom_boxplot()\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-3-2.png){fig-align='center' width=672}\n:::\n:::\n\n\nThis immediately gives us a nice boxplot. Note that if we'd try to use this command after loading in **gender** as character rather than factor data, ***R*** would have thrown an error.\n\nBased on our plot, there indeed seems to be a difference in height between males and females. We can test this directly using linear regression (and, recall, we already know another way to test this, using $Z$ or t tests to compare means).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm <- lm(data = z, height ~ gender)\n```\n:::\n\n\nIf we take a look at the `summary()` of our model, **m**, we see the same kind of table of results we have seen before, but because the predictor variable in this case is a factor vector instead of a numeric vector, the coefficients are reported and interpreted a bit differently.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = height ~ gender, data = z)\n## \n## Residuals:\n##      Min       1Q   Median       3Q      Max \n## -15.4642  -2.4861   0.0876   2.5425  11.0065 \n## \n## Coefficients:\n##             Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)  65.5983     0.1717  382.13   <2e-16 ***\n## genderMale    4.0154     0.2413   16.64   <2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 3.815 on 998 degrees of freedom\n## Multiple R-squared:  0.2172,\tAdjusted R-squared:  0.2164 \n## F-statistic: 276.9 on 1 and 998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe coefficient for the intercept, i.e., $\\beta_0$, reflects the estimate of the mean height for the first of our level variables.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlevels(z$gender)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] \"Female\" \"Male\"\n```\n\n\n:::\n:::\n\n\nThe estimate for $\\beta_1$ is reported as \"genderMale\" and the value for that coefficient, 4.0154, is the estimated difference in mean height associated with being a male. The regression equation is basically:\n\n$$height = 65.5983 + 4.0154 \\times gender$$\n\nwith males assigned a gender value of 1 and females of 0.\n\nIn this case, the p value associated with the **t statistic** for $\\beta_1$ is extremely low, so we conclude that **gender** has a significant effect on **height**.\n\nWe can easily `relevel()` what is the baseline group. The result is very similar, but the sign of $\\beta_1$ is changed.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nz$gender <- relevel(z$gender, ref = \"Male\")\nm <- lm(data = z, height ~ gender)\nsummary(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = height ~ gender, data = z)\n## \n## Residuals:\n##      Min       1Q   Median       3Q      Max \n## -15.4642  -2.4861   0.0876   2.5425  11.0065 \n## \n## Coefficients:\n##              Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)   69.6137     0.1696  410.42   <2e-16 ***\n## genderFemale  -4.0154     0.2413  -16.64   <2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 3.815 on 998 degrees of freedom\n## Multiple R-squared:  0.2172,\tAdjusted R-squared:  0.2164 \n## F-statistic: 276.9 on 1 and 998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nThe last line of the `summary()` output shows the results of the global test of significance of the regression model based on an F statistic compared to an F distribution with, in this case, 1 and 998 degrees of freedom.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np <- 1 - pf(q = 276.9, df1 = 1, df2 = 998)\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0\n```\n\n\n:::\n:::\n\n\nWe can extend this approach to the case where we have more than two categories for a variable... in this case we need to dummy code our factor variable into multiple binary variables. ***R*** takes care of this for us automatically, but it is good to recognize the procedure.\n\nLet's explore this by re-coding the variable **major** into four levels. We can first use the `unique()` or `levels()` function to list all of the different majors in our dataset. The latter does this alphabetically.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nunique(z$major)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##  [1] medicine/nursing                      criminal justice administration      \n##  [3] education                             energy studies                       \n##  [5] logistics                             psychology                           \n##  [7] botany                                communication                        \n##  [9] military strategy                     economics                            \n## [11] mechanical engineering                physical education                   \n## [13] philosophy                            biology                              \n## [15] applied sciences                      animal husbandry                     \n## [17] agricultural sciences                 culinary services                    \n## [19] city planning                         integrated water resources management\n## [21] pharmacology                          environmental science                \n## [23] human services                        epidemiology                         \n## [25] business administration               architecture                         \n## 26 Levels: agricultural sciences animal husbandry ... psychology\n```\n\n\n:::\n\n```{.r .cell-code}\nlevels(z$major)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##  [1] \"agricultural sciences\"                \n##  [2] \"animal husbandry\"                     \n##  [3] \"applied sciences\"                     \n##  [4] \"architecture\"                         \n##  [5] \"biology\"                              \n##  [6] \"botany\"                               \n##  [7] \"business administration\"              \n##  [8] \"city planning\"                        \n##  [9] \"communication\"                        \n## [10] \"criminal justice administration\"      \n## [11] \"culinary services\"                    \n## [12] \"economics\"                            \n## [13] \"education\"                            \n## [14] \"energy studies\"                       \n## [15] \"environmental science\"                \n## [16] \"epidemiology\"                         \n## [17] \"human services\"                       \n## [18] \"integrated water resources management\"\n## [19] \"logistics\"                            \n## [20] \"mechanical engineering\"               \n## [21] \"medicine/nursing\"                     \n## [22] \"military strategy\"                    \n## [23] \"pharmacology\"                         \n## [24] \"philosophy\"                           \n## [25] \"physical education\"                   \n## [26] \"psychology\"\n```\n\n\n:::\n:::\n\n\nWe can then also do some cool batch recoding using the `%in%` operator and the `mutate()` function from {dplyr}...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nz <- z |>\n  mutate(\n    occupation = case_when(\n      major %in% c(\n        \"agricultural sciences\",\n        \"animal husbandry\",\n        \"applied sciences\",\n        \"biology\",\n        \"botany\",\n        \"energy studies\",\n        \"environmental science\",\n        \"epidemiology\",\n        \"medicine/nursing\",\n        \"pharmacology\"\n      ) ~ \"natural science\",\n      major %in% c(\n        \"business administration\",\n        \"city planning\",\n        \"economics\",\n        \"human services\",\n        \"logistics\",\n        \"military strategy\"\n      ) ~ \"logistics\",\n      major %in% c(\n        \"architecture\",\n        \"integrated water resources management\",\n        \"mechanical engineering\"\n      ) ~ \"engineering\",\n      major %in% c(\n        \"communication\",\n        \"criminal justice administration\",\n        \"culinary services\",\n        \"education\",\n        \"philosophy\",\n        \"physical education\",\n        \"psychology\"\n      ) ~ \"other\"\n    )\n  )\nz$occupation <- factor(z$occupation) # can also use `as.factor()`\nlevels(z$occupation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] \"engineering\"     \"logistics\"       \"natural science\" \"other\"\n```\n\n\n:::\n\n```{.r .cell-code}\nz$occupation <- relevel(z$occupation, ref = \"natural science\")\nlevels(z$occupation)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] \"natural science\" \"engineering\"     \"logistics\"       \"other\"\n```\n\n\n:::\n:::\n\n\nAgain, we can plot our variable by group and run a multilevel linear regression. Each $\\beta$ estimate reflects the difference from the estimated mean for the reference level. The `lm()` function also returns the results of the global significance test of our model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(data = z, zombies_killed ~ occupation)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-11-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\nm <- lm(data = z, zombies_killed ~ occupation)\nsummary(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = zombies_killed ~ occupation, data = z)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -3.3061 -1.0068 -0.0068  1.0092  8.0974 \n## \n## Coefficients:\n##                       Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)            2.90256    0.08848  32.804   <2e-16 ***\n## occupationengineering  0.40356    0.19745   2.044   0.0412 *  \n## occupationlogistics    0.08826    0.14777   0.597   0.5504    \n## occupationother        0.10424    0.13496   0.772   0.4401    \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 1.747 on 996 degrees of freedom\n## Multiple R-squared:  0.004209,\tAdjusted R-squared:  0.00121 \n## F-statistic: 1.403 on 3 and 996 DF,  p-value: 0.2403\n```\n\n\n:::\n\n```{.r .cell-code}\np <- 1 - pf(q = 0.489, df1 = 3, df2 = 996) # F test\np\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.6899872\n```\n\n\n:::\n:::\n\n\nIn this case, we see no significant effect of **occupation** (based on a broad categorization of college major) on zombie killing proficiency.\n\n## One-Way ANOVA\n\nRegression with a single categorical predictor run as we have just done above is exactly equivalent to a \"One-Way\" or \"one-factor\" Analysis of Variance, or ANOVA. That is, ANOVA is just one type of special case of least squares regression.\n\nWe can, of course, run an ANOVA with one line in ***R***. Compare the results presented in the `summary()` output table (or `tidy()` output table) from an ANOVA with that from the global test reported in `summary()` (or `tidy()`) from `lm()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.aov <- aov(data = z, zombies_killed ~ occupation)\nsummary(m.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value Pr(>F)\n## occupation    3   12.9   4.285   1.403   0.24\n## Residuals   996 3041.1   3.053\n```\n\n\n:::\n\n```{.r .cell-code}\ntidy(m.aov) # a neater table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 2 × 6\n##   term          df  sumsq meansq statistic p.value\n##   <chr>      <dbl>  <dbl>  <dbl>     <dbl>   <dbl>\n## 1 occupation     3   12.9   4.28      1.40   0.240\n## 2 Residuals    996 3041.    3.05     NA     NA\n```\n\n\n:::\n\n```{.r .cell-code}\nm.lm <- lm(data = z, zombies_killed ~ occupation)\nsummary(m.lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = zombies_killed ~ occupation, data = z)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -3.3061 -1.0068 -0.0068  1.0092  8.0974 \n## \n## Coefficients:\n##                       Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)            2.90256    0.08848  32.804   <2e-16 ***\n## occupationengineering  0.40356    0.19745   2.044   0.0412 *  \n## occupationlogistics    0.08826    0.14777   0.597   0.5504    \n## occupationother        0.10424    0.13496   0.772   0.4401    \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 1.747 on 996 degrees of freedom\n## Multiple R-squared:  0.004209,\tAdjusted R-squared:  0.00121 \n## F-statistic: 1.403 on 3 and 996 DF,  p-value: 0.2403\n```\n\n\n:::\n\n```{.r .cell-code}\ntidy(m.lm) # a neater table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 4 × 5\n##   term                  estimate std.error statistic   p.value\n##   <chr>                    <dbl>     <dbl>     <dbl>     <dbl>\n## 1 (Intercept)             2.90      0.0885    32.8   1.27e-160\n## 2 occupationengineering   0.404     0.197      2.04  4.12e-  2\n## 3 occupationlogistics     0.0883    0.148      0.597 5.50e-  1\n## 4 occupationother         0.104     0.135      0.772 4.40e-  1\n```\n\n\n:::\n\n```{.r .cell-code}\npar(mfrow = c(2, 2))\nplot(m.lm) # plot(m.aov) is equivalent\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nThese two model summaries produce somewhat different tables for the same analysis. The **F statistic** and omnibus p value given in the `aov()` ANOVA table indicates whether there are differences between at least some treatments, but we do not know where those differences occur. The summary from `lm()` shows the effects of the categorical treatments arranged as sequential contrasts (the default in R). The first row gives the mean of the first level of the first factor specified in the model. The following rows give differences **from this first mean** for each subsequent factor level. Likewise the standard error in the first row is a standard error of a mean, while the entries in subsequent rows are standard errors of the differences between two means.\n\nIn general, in ANOVA and simple regression using a single categorical variable, we aim to test the $H_0$ that the means of a variable of interest do not differ among groups, i.e., that $\\mu_1 = \\mu_2 = ... = \\mu_k$ are all equal. This is an extension of our comparison of two means that we did with z and t tests.\n\nThe basic linear model formulation for ANOVA is:\n\n$$Y_{i,j} = \\mu + \\beta_i X_i + \\epsilon_{i,j}$$\n\nwhere:\n\n- $\\mu$ is the grand (overall) population mean\n- $\\beta_i$ is the deviation of the mean of treatment level $i$ from the grand mean\n- $\\epsilon_{i,j}$ is error variance of individual points, $j$, within each level, $i$, from the grand mean\n\nThe assumptions of ANOVA, similar to those of simple regression, are:\n\n- that samples are independent and identically distributed ($iid$)\n- that the residuals, $\\epsilon_{i,j}$, are normally distributed\n- that within-group variances are similar across all groups (\"homoscedastic\")\n\nAdditionally, the following assumption of standard ANOVA makes the interpretation of results more straightforward, but it is not strictly required...\n\n- that our experiment/observations have a balanced design (i.e., an equal number of cases in all groups)\n\nIf this last assumption is violated, it ceases to be true that the **total SS of our dataset = within group SS + between group SS**, and then the calculations of our MSE and the F statistic, and our associated p value, would be off.\n\n## Simulation-Based Inference\n\nNote that the ANOVA functions used above (`aov()`, `lm()`) are evaluating statistical significance and estimating p values based on mathematical theory, i.e., by comparing F statistic values to a theoretical, parametric $F$ distribution to determine how likely we are to see an F statistic as extreme as our observed one by chance under the null model of no difference between groups. However, as with other tests of statistical inference, we can also use permutation/randomization methods to determine p values for ANOVA.\n\nOne easy way to do this is with the {infer} package. Using {infer}, we can easily permute, a large number of times, the association between our response variable the categorical explanatory variable and, each time, then calculate the associated F statistic. This generates a permutation-based null distribution of F statistics to which we can compare the F statistic generated from our original data. The permutation-based p value is then the proportion of F statistic values generated by simulation that are equal to or greater than our observed F statistic value.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noriginal.F <- aov(data = z, zombies_killed ~ occupation) |>\n  tidy() |>\n  filter(term == \"occupation\")\n# show aov results for F statistic and p value for omnibus F test\noriginal.F\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 1 × 6\n##   term          df sumsq meansq statistic p.value\n##   <chr>      <dbl> <dbl>  <dbl>     <dbl>   <dbl>\n## 1 occupation     3  12.9   4.28      1.40   0.240\n```\n\n\n:::\n\n```{.r .cell-code}\npermuted.F <- z |>\n  # specify model\n  specify(zombies_killed ~ occupation) |>\n  # null hypothesis of independence\n  hypothesize(null = \"independence\") |>\n  # generate permutations\n  generate(reps = 1000, type = \"permute\") |>\n  # calculate the F statistic for the AOV\n  calculate(stat = \"F\")\n\n# plot our F statistic on the distribution of F statistic values generated by permutation\nvisualize(permuted.F) +\n  shade_p_value(obs_stat = original.F$statistic, direction = \"greater\")\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n(\n  p.value <- permuted.F |>\n    get_p_value(obs_stat = original.F$statistic, direction = \"greater\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 1 × 1\n##   p_value\n##     <dbl>\n## 1    0.24\n```\n\n\n:::\n:::\n\n\nNote that, for these data, the p value estimated through simulation-based inference is very similar to that calculated parameterically based on mathematical theory. This is not always the case!\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noriginal.F$p.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.2403441\n```\n\n\n:::\n\n```{.r .cell-code}\np.value\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 1 × 1\n##   p_value\n##     <dbl>\n## 1    0.24\n```\n\n\n:::\n:::\n\n\nAlternatively, the {permuco} package introduces the `aovperm()` and `lmperm()` functions as analogs for `aov()` and `lm()` for analysis of variance and simple linear regression, where p values are calculated by permutation.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(permuco)\nm.aovperm <- aovperm(data = z, zombies_killed ~ occupation)\nsummary(m.aovperm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Anova Table\n## Resampling test using freedman_lane to handle nuisance variables and 5000 permutations.\n##                 SS  df     F parametric P(>F) resampled P(>F)\n## occupation   12.85   3 1.403           0.2403           0.237\n## Residuals  3041.08 996\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(m.aovperm)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\nm.lmperm <- lmperm(data = z, zombies_killed ~ occupation)\nsummary(m.lmperm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Table of marginal t-test of the betas\n## Resampling test using freedman_lane to handle nuisance variables and 5000 permutations.\n##                       Estimate Std. Error t value parametric Pr(>|t|)\n## (Intercept)            2.90256    0.08848 32.8042          1.269e-160\n## occupationengineering  0.40356    0.19745  2.0439           4.123e-02\n## occupationlogistics    0.08826    0.14777  0.5973           5.504e-01\n## occupationother        0.10424    0.13496  0.7724           4.401e-01\n##                       resampled Pr(<t) resampled Pr(>t) resampled Pr(>|t|)\n## (Intercept)                                                               \n## occupationengineering           0.9800           0.0202             0.0402\n## occupationlogistics             0.7176           0.2826             0.5490\n## occupationother                 0.7806           0.2196             0.4286\n```\n\n\n:::\n\n```{.r .cell-code}\ndetach(package:permuco)\n```\n:::\n\n\nSimilar to {infer}, the {coin} package also implements permutation-based tests of independence, including One-Way ANOVA. Instead of F statistics, the test statistic implemented in {coin} is a **Chi-Square statistic** (which is essentially to equivalent to an F statistic, normalized by the residual degrees of freedom), and it is tested against a permutation-based null distribution of Chi-Square values.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(coin)\nm.aov <- oneway_test(data = z, zombies_killed ~ occupation, distribution = \"approximate\")\n# by default, 10000 replicates are used\nm.aov\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tApproximative K-Sample Fisher-Pitman Permutation Test\n## \n## data:  zombies_killed by\n## \t occupation (natural science, engineering, logistics, other)\n## chi-squared = 4.2048, p-value = 0.239\n```\n\n\n:::\n\n```{.r .cell-code}\ndetach(package:coin)\n```\n:::\n\n\n### CHALLENGE {.unnumbered}\n\nLoad in the \"gibbon-femurs.csv\" dataset, which contains the lengths, in centimeters, of the femurs of 400 juvenile, subadult, and adult individuals gibbons. Use both ANOVA and simple linear regression to examine the relationship between age and femur length.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf <- \"https://raw.githubusercontent.com/difiore/ada-datasets/main/gibbon-femurs.csv\"\nd <- read_csv(f, col_names = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n## Rows: 525 Columns: 4\n## ── Column specification ────────────────────────────────────────────────────────\n## Delimiter: \",\"\n## chr (2): age, sex\n## dbl (2): id, femur_length\n## \n## ℹ Use `spec()` to retrieve the full column specification for this data.\n## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\nd$age <- factor(d$age, levels = c(\"inf\", \"juv\", \"subadult\", \"adult\"))\n# converts age to a factor and order the age levels so that they are in ascending chronological order\n# several ANOVA functions require that categorical variables are represented as factors rather than as strings\nd$sex <- factor(d$sex, levels = c(\"female\", \"male\"))\n# convert sex to a factor\nhead(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 4\n##      id age   sex    femur_length\n##   <dbl> <fct> <fct>         <dbl>\n## 1     1 inf   female         7.28\n## 2     2 inf   male           6.3 \n## 3     3 inf   female         7.44\n## 4     4 inf   male           8.69\n## 5     5 inf   female         9.13\n## 6     6 inf   male           9.28\n```\n\n\n:::\n:::\n\n\nBefore beginning, check for normality of data overall...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\npar(mfrow = c(1, 2))\nhist(d$femur_length)\nqqnorm(d$femur_length)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-18-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# not great overall...\n```\n:::\n\n\nThen, do a boxplot of the data by each age group and check for normality within each group.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nplot(data = d, femur_length ~ age) # boxplot with medians\n\n# calculate average and SD by group\nstats <- d |>\n  group_by(age) |>\n  summarize(\n    \"mean(femur_length)\" = mean(femur_length),\n    \"sd(femur_length)\" = sd(femur_length)\n  )\n\n# add means to plot\npoints(1:4, stats$`mean(femur_length)`, pch = 4, cex = 1.5)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=384}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\n# subtract relevant group mean from each data point\nmeans.centered <- d$femur_length - stats[as.numeric(d$age), 2]\n\n# graphical test for normality of group-centered means\nqqnorm(means.centered$`mean(femur_length)`) # looks good!\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-19-2.png){fig-align='center' width=384}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\n# now do graphical test within each group\npar(mfrow = c(1, 2))\nhist(d$femur_length[d$age == \"inf\"],\n  main = \"Infant\",\n  xlab = \"Femur Length (cm)\"\n)\nqqnorm(d$femur_length[d$age == \"inf\"])\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-19-3.png){fig-align='center' width=384}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nhist(d$femur_length[d$age == \"juv\"],\n  main = \"Juvenile\",\n  xlab = \"Femur Length (cm)\"\n)\nqqnorm(d$femur_length[d$age == \"juv\"])\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-19-4.png){fig-align='center' width=384}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nhist(d$femur_length[d$age == \"subadult\"],\n  main = \"Subadult\",\n  xlab = \"Femur Length (cm)\"\n)\nqqnorm(d$femur_length[d$age == \"subadult\"])\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-19-5.png){fig-align='center' width=384}\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\nhist(d$femur_length[d$age == \"adult\"],\n  main = \"Adult\",\n  xlab = \"Femur Length (cm)\"\n)\nqqnorm(d$femur_length[d$age == \"adult\"])\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-19-6.png){fig-align='center' width=384}\n:::\n:::\n\n\nAlso, check whether the different groups have roughly equal variances. As a general rule of thumb, we can compare the largest and smallest within-group standard deviations; if the ratio of max-to-min is less, than 2 then the assumption of \"equal\" variances is usually reasonable.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\n# check that variances are roughly equal (ratio of max/min is <2)\nmax(stats$`sd(femur_length)`) / min(stats$`sd(femur_length)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{.details summary=\"Show Output\"}\n## [1] 1.767635\n```\n\n\n:::\n:::\n\n\nAll this checking done, we can again plot our data by group and then run our linear or ANOVA model...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\nplot(\n  data = d, femur_length ~ age,\n  xlab = \"Age\", ylab = \"Femur Length (cm)\"\n)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\nm <- lm(data = d, femur_length ~ age)\nsummary(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = femur_length ~ age, data = d)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -5.2052 -1.1104  0.1089  1.0396  5.6748 \n## \n## Coefficients:\n##             Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)   7.7104     0.1180   65.32   <2e-16 ***\n## agejuv        2.3406     0.1803   12.98   <2e-16 ***\n## agesubadult   6.0460     0.2045   29.57   <2e-16 ***\n## ageadult      9.7147     0.2260   42.98   <2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 1.669 on 521 degrees of freedom\n## Multiple R-squared:  0.809,\tAdjusted R-squared:  0.8079 \n## F-statistic: 735.8 on 3 and 521 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nm.aov <- aov(data = d, femur_length ~ age) # femur length related to age\nsummary(m.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value Pr(>F)    \n## age           3   6152  2050.6   735.8 <2e-16 ***\n## Residuals   521   1452     2.8                   \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nIs the omnibus test of the relationship between age category and femur length significant? YES! Are femur lengths significantly different for juveniles versus subadults? Subadults versus adults? Juveniles versus adults?\n\n> **HINT:** To test some of these additional bivariate options, you will need to `relevel()` your factors for simple linear regression. Currently, we are just testing each group relative to the first level of the factor **age**.\n\n## Post-Hoc Tests in ANOVA\n\nAfter finding a significant omnibus F statistic in an ANOVA, we can test, post-hoc, what group means are different from one another using **pairwise t tests** with an appropriate p value correction for multiple tests.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npairwise.t.test(d$femur_length, d$age, p.adj = \"bonferroni\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tPairwise comparisons using t tests with pooled SD \n## \n## data:  d$femur_length and d$age \n## \n##          inf    juv    subadult\n## juv      <2e-16 -      -       \n## subadult <2e-16 <2e-16 -       \n## adult    <2e-16 <2e-16 <2e-16  \n## \n## P value adjustment method: bonferroni\n```\n\n\n:::\n:::\n\n\nAfter an ANOVA, we can also use a **Tukey Honest Significant Differences** test with the model as the argument to evaluate this.\n\n> **NOTE:** The `TukeyHSD()` function is run on the output of the ANOVA (`aov()`) function.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# renaming age categories so we get nice axis labels on plot...\nd <- d |>\n  mutate(age = case_when(\n    age == \"adult\" ~ \"A\",\n    age == \"subadult\" ~ \"S\",\n    age == \"juv\" ~ \"J\",\n    age == \"inf\" ~ \"I\"\n  )) |>\n  # and coerce age back to being a factor\n  mutate(age = factor(age, level = c(\"I\", \"J\", \"S\", \"A\")))\n\nm.aov <- aov(femur_length ~ age, data = d)\nposthoc <- TukeyHSD(m.aov,\n  which = \"age\",\n  ordered = TRUE,\n  conf.level = 0.95\n)\nposthoc # all age-sex classes differ\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##   Tukey multiple comparisons of means\n##     95% family-wise confidence level\n##     factor levels have been ordered\n## \n## Fit: aov(formula = femur_length ~ age, data = d)\n## \n## $age\n##         diff      lwr       upr p adj\n## J-I 2.340617 1.875875  2.805359     0\n## S-I 6.045950 5.518982  6.572918     0\n## A-I 9.714750 9.132165 10.297335     0\n## S-J 3.705333 3.149860  4.260806     0\n## A-J 7.374133 6.765643  7.982623     0\n## A-S 3.668800 3.011556  4.326044     0\n```\n\n\n:::\n:::\n\n\nWe can get a visual summary of difference in means between each group and their confidence intervals by passing the Tukey test output to a `plot()` function. Confidence intervals that cross the vertical line indicate pairs of groups where the difference in mean is not significant, according to the threshold we set.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nplot(posthoc, xlim = c(-2, 12)) # xlim set to show zero\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-24-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n## A Non-Parametric Alternative\n\nThe **Kruskal-Wallis** test is a nonparametric alternative to One-Way ANOVA that relaxes the need for normality in the distribution of data in each group (the different groups should still have roughly equal variances). Essentially, rather than testing the null hypothesis that the means for each group do not differ we are instead testing the null hypothesis that the **medians** do not differ. The test converts the continuous response variable to a set of RANKS (i.e., it does a uniform transformation) and then works with those ranks. The **p** value associated with the Kruskall-Wallis test statistic is calculated mathematically relative to a Chi-Square distribution.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(m.kruskal <- kruskal.test(data = d, femur_length ~ age))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tKruskal-Wallis rank sum test\n## \n## data:  femur_length by age\n## Kruskal-Wallis chi-squared = 407.13, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# to show that this is the same as the test using ranks...\n# use {dplyr} to sort by femur.length...\nd <- arrange(d, femur_length)\n# then use {dplyr} to add new variable of rank femur_length\nd <- mutate(d, femur_rank = row(data.frame(d$femur_length)))\n(m.kruskal <- kruskal.test(data = d, femur_rank ~ age))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tKruskal-Wallis rank sum test\n## \n## data:  femur_rank by age\n## Kruskal-Wallis chi-squared = 407.43, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n:::\n\n\nFor a post-hoc test of which groups are different following a Kruskall-Wallis test, we can use either a pairwise Mann-Whitney U test, a Dunn test, or a Conover-Iman test. The latter two tests are implemented using `dunn.test()` from the {dunn.test} package or `conover.test()` from the {conover.test} package, which both allow us to show the calculated Krusal-Wallis test statistic as well.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# pairwise Mann-Whitney U test\n# the arguments are a vector of data, a vector with the grouping factor, and the multiple test correction method...\npairwise.wilcox.test(d$femur_length, d$age,\n  p.adjust.method = \"bonferroni\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tPairwise comparisons using Wilcoxon rank sum test with continuity correction \n## \n## data:  d$femur_length and d$age \n## \n##   I      J      S     \n## J <2e-16 -      -     \n## S <2e-16 <2e-16 -     \n## A <2e-16 <2e-16 <2e-16\n## \n## P value adjustment method: bonferroni\n```\n\n\n:::\n\n```{.r .cell-code}\n# `dunn.test()` and `conover.test()` include another argument, `kw=`, which is whether or not to output KW results\nlibrary(dunn.test)\ndunn.test(d$femur_length, g = d$age, method = \"bonferroni\", kw = TRUE)\ndetach(package:dunn.test)\nlibrary(conover.test)\nconover.test(d$femur_length, g = d$age, method = \"bonferroni\", kw = TRUE)\ndetach(package:conover.test)\n```\n:::\n\n\n### Effect Sizes\n\nWe can apply the `effectsize()` function from the {effectsize} package to our model objects to better interpret the meaning of our coefficients.\n\nFor an ANOVA, the effect sizes represent the amount of variance in the response variable explained by each of the model’s terms. For this model, we are asking what percent of the total variance in **femur length** is explained by the categorical variable of **age** class. This measure is called $\\eta^2$ (\"eta-squared\") and is analogous to r-squared.\n\n$$\\eta^2 = \\frac{SS_{predictor}}{SS_{total}} = \\frac{SS_{predictor}}{SS_{predictor} + SS_{residuals}}$$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neffectsize(m.aov)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n## For one-way between subjects designs, partial eta squared is equivalent\n##   to eta squared. Returning eta squared.\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # Effect Size for ANOVA\n## \n## Parameter | Eta2 |       95% CI\n## -------------------------------\n## age       | 0.81 | [0.79, 1.00]\n## \n## - One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\n# or `eta_squared(m.aov)`\n# we can hand-calculate this same value from the ANOVA table as 6152/(6152 + 1452)\n```\n:::\n\n\nHere, 81% of the variance in **femur length** is accounted for by variance in the grouping variable **age**.\n\nApplied to a linear model object, the `effectsize()` function refits the model and returns **standardized** coefficients rather than unstandardized ones. This is equivalent to running the original linear model after standardizing all of the variables so that they are represented on the same scale, which is typically done via a $Z$ transformation (i.e., by subtracting its mean from each variable observation and divide by its standard deviation): $z_i = \\frac{x_i - \\mu_x}{SD_x}$\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm <- lm(femur_length ~ age, data = d)\neffectsize(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # Standardization method: refit\n## \n## Parameter   | Std. Coef. |         95% CI\n## -----------------------------------------\n## (Intercept) |      -0.84 | [-0.90, -0.78]\n## age [J]     |       0.61 | [ 0.52,  0.71]\n## age [S]     |       1.59 | [ 1.48,  1.69]\n## age [A]     |       2.55 | [ 2.43,  2.67]\n```\n\n\n:::\n:::\n\n\n> **NOTE**: The {datawizard} package provides the function `standardize()`, which will also take a model and refit it using standardized parameters and return a refitted model object.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(datawizard)\nstandardize(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = femur_length ~ age, data = data_std)\n## \n## Coefficients:\n## (Intercept)         ageJ         ageS         ageA  \n##     -0.8422       0.6144       1.5871       2.5502\n```\n\n\n:::\n\n```{.r .cell-code}\ndetach(package:datawizard)\n```\n:::\n\n\n## Multiple Factor ANOVA\n\nSometimes the data we are interested in is characterized by multiple grouping variables (e.g., **age** and **sex**). In the case of the gibbon femur length data, we are interested in the **main effect** of each factor on the variable of interest (e.g., do femur lengths vary by **age** or **sex**) while accounting for the effects of the other factor. We may also be interested in any **interactive effects** among factors. Thus, in multiple factor ANOVA we are interested in testing several null hypotheses simultaneously: [1] that each factor has no effect on the mean of our continuous response variable and [2] that there are no interactive effects of sets of factors on the mean of our continuous response variable.\n\nModel description and testing for multiple-factor ANOVA is a simple extension of the formula notation which we've used for single factors. First, though, let's quickly check that our groups have similar variance.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nstats <- d |>\n  group_by(age, sex) |>\n  summarize(\n    \"mean(femur_length)\" = mean(femur_length),\n    \"sd(femur_length)\" = sd(femur_length)\n  )\n# first we calculate averages by combination of factors\nmax(stats$`sd(femur_length)`) / min(stats$`sd(femur_length)`)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1.882171\n```\n\n\n:::\n\n```{.r .cell-code}\n# check that variances in each group are roughly equal (ratio of max/min is <2)\np <- ggplot(data = d, aes(y = femur_length, x = sex)) +\n  geom_boxplot() +\n  facet_wrap(~age, ncol = 4) +\n  xlab(\"Sex\") +\n  ylab(\"Femur Length (cm)\")\n# and let's plot what the data look like\n# p <- p + geom_point() # uncommenting this shows all points\np <- p + stat_summary(\n  data = d, aes(y = femur_length, x = sex),\n  fun = base::mean, color = \"darkgreen\", geom = \"point\", shape = 8, size = 6\n)\n# make sure we use {base} version of mean\np\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-30-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nIf we look at each variable separately using ANOVA, we see there is an effect of **age** but not of **sex**.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(aov(data = d, femur_length ~ age))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value Pr(>F)    \n## age           3   6152  2050.6   735.8 <2e-16 ***\n## Residuals   521   1452     2.8                   \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(aov(data = d, femur_length ~ sex))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value Pr(>F)\n## sex           1     28   28.33   1.956  0.163\n## Residuals   523   7576   14.48\n```\n\n\n:::\n:::\n\n\nHowever, if we do a Two-Way ANOVA and consider the factors together, we see that there is still a main effect of **age** when taking **sex** into account **and** there is a main effect of **sex** when we take **age** into account.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.aov <- aov(data = d, femur_length ~ age + sex)\nm.aov\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Call:\n##    aov(formula = femur_length ~ age + sex, data = d)\n## \n## Terms:\n##                      age      sex Residuals\n## Sum of Squares  6151.837   42.301  1409.713\n## Deg. of Freedom        3        1       520\n## \n## Residual standard error: 1.646507\n## Estimated effects may be unbalanced\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(m.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value   Pr(>F)    \n## age           3   6152  2050.6   756.4  < 2e-16 ***\n## sex           1     42    42.3    15.6 8.89e-05 ***\n## Residuals   520   1410     2.7                     \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWhen we run `effectsize()` on a model object resulting from a multiple factor ANOVA, the function, by default, returns partial $\\eta^2$ values, which is the proportion of the variance in the response variable that is accounted by each categorical predictor *when controlling for the other predictors*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\neffectsize(m.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # Effect Size for ANOVA (Type I)\n## \n## Parameter | Eta2 (partial) |       95% CI\n## -----------------------------------------\n## age       |           0.81 | [0.79, 1.00]\n## sex       |           0.03 | [0.01, 1.00]\n## \n## - One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\n# or effectsize(m.aov, partial = TRUE)\n```\n:::\n\n\n### Interaction Terms\n\nTo examine whether there is an interaction effect between our multiple categorical predicto variables, we would modify our model formula a bit using the colon operator (`:`) to specify a particular interaction term...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.aov <- aov(data = d, femur_length ~ age + sex + age:sex)\n# the colon (:) operator includes specific interaction terms\nsummary(m.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value   Pr(>F)    \n## age           3   6152  2050.6  816.35  < 2e-16 ***\n## sex           1     42    42.3   16.84 4.72e-05 ***\n## age:sex       3    111    37.0   14.73 3.21e-09 ***\n## Residuals   517   1299     2.5                     \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe could also use the asterisk (`*`) operator, which expands to include all interactions among terms, including 3-way, 4-way, etc., interactions.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm.aov <- aov(data = d, femur_length ~ age * sex)\n# asterisk (*) operator includes all interaction terms\nsummary(m.aov)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value   Pr(>F)    \n## age           3   6152  2050.6  816.35  < 2e-16 ***\n## sex           1     42    42.3   16.84 4.72e-05 ***\n## age:sex       3    111    37.0   14.73 3.21e-09 ***\n## Residuals   517   1299     2.5                     \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# or using the lm() function...\nm <- lm(data = d, femur_length ~ age * sex)\nsummary(m)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = femur_length ~ age * sex, data = d)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -5.8727 -1.0088  0.1336  1.0469  4.6773 \n## \n## Coefficients:\n##              Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)    7.8250     0.1562  50.107  < 2e-16 ***\n## ageJ           2.1514     0.2354   9.140  < 2e-16 ***\n## ageS           4.8481     0.2832  17.118  < 2e-16 ***\n## ageA           8.8909     0.2854  31.148  < 2e-16 ***\n## sexmale       -0.2363     0.2242  -1.054    0.293    \n## ageJ:sexmale   0.3986     0.3431   1.162    0.246    \n## ageS:sexmale   2.2059     0.3896   5.662 2.48e-08 ***\n## ageA:sexmale   1.9523     0.4341   4.498 8.48e-06 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 1.585 on 517 degrees of freedom\n## Multiple R-squared:  0.8292,\tAdjusted R-squared:  0.8269 \n## F-statistic: 358.6 on 7 and 517 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nNote that when we run `summary()` on the results of the `lm()` function (as opposed to running it on the results of the `aov()` function), we are estimating eight $\\beta$ coefficients (equivalent to the number of groups we have). Here, $\\beta_0$, the intercept, is the mean femur length for the base level (in this case, \"adult females\"). Then we have coefficients showing how the different factor combination groups would differ from that base level (e.g., adult males have mean femur lengths 1.716 greater than adult females, etc).\n\n### Visualizing Interactions\n\nWe can use the function `interaction.plot()` to visualize interactions among categorical variables in our raw data...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ninteraction.plot(\n  x.factor = factor(d$age, level = c(\"I\", \"J\", \"S\", \"A\")),\n  xlab = \"Age\",\n  trace.factor = d$sex,\n  trace.label = \"Sex\",\n  response = d$femur_length,\n  fun = base::mean,\n  ylab = \"Mean Femur Length\"\n)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-36-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nHere, it appears like there is indeed a significant main effect of each term (within several the adult and subadult categories, mean femur length differs for males and females), as well as an interaction between our two categorical variables (the same does not appear to be true for infants and juveniles).\n\nWe can also use either the {sjPlot} or {emmeans} packages to look at differences in **Mean Femur Length** predicted by our multiple ANOVA model. These plot the estimated marginal means, or the average predicted scores scores for each independent variable at a given level of the other independent variable...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sjPlot)\nplot_model(m.aov,\n  type = \"emm\",\n  terms = c(\"age\", \"sex\")\n)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-37-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\ndetach(package:sjPlot)\nlibrary(emmeans)\nemmip(m.aov,\n  sex ~ age,\n  CIs = TRUE\n)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-37-2.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\ndetach(package:emmeans)\n```\n:::\n\n\nNote that these plots show the model-predicted mean value for the response variable **femur length** for each combination of the two categorical predictors (**age** and **sex**).\n\n- Differences between points at a given **age** indicate an effect of **sex** within that particular **age** category.\n- Non-parallel lines in the interaction plot (like we have here) indicate an interaction between predictors. If one **sex** has a very different pattern across **age** than the other, then that is evidence that the interaction term is meaningful (and, in this case, would suggest that developmental trajectories differ by **sex**). Parallel lines would suggest no interaction (and, thus, that developmental trajectories are similar in the two sexes).\n- Crossing lines in a marginal means plot would indicate a strong interaction among predictor terms, e.g., where the ranking of **femur length** by **sex** actually reverses with **age** class.\n\nWe will return to comparing alternative ANOVA models to one another (e.g., our model with and without interaction terms) and to post-hoc tests of which group mean differences are significant when we get into model selection in [**Module 22**](#module-22).\n\nThe {permuco} package also lets us run multiple factor ANOVA using permutation/randomization to estimate p values.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(permuco)\nm.aovperm <- aovperm(data = d, femur_length ~ age + sex + age:sex)\nsummary(m.aovperm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Anova Table\n## Resampling test using freedman_lane to handle nuisance variables and 5000 permutations.\n##               SS  df      F parametric P(>F) resampled P(>F)\n## age       6136.3   3 814.28        0.000e+00           2e-04\n## sex         91.7   1  36.51        2.914e-09           2e-04\n## age:sex    111.0   3  14.73        3.210e-09           2e-04\n## Residuals 1298.7 517\n```\n\n\n:::\n\n```{.r .cell-code}\ndetach(package:permuco)\n```\n:::\n\n\n## Type I, II, and III ANOVA\n\nIt is important to recognize that the **order** in which our factors are entered into a linear model using multiple categorical predictors can result in different values for the entries in our ANOVA table, while the estimation of our regression coefficients is identical regardless. Take a look at this example, where the variables **age** and **sex** are entered into our ANOVA formula in different orders:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nm1 <- aov(data = d, femur_length ~ age + sex)\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value   Pr(>F)    \n## age           3   6152  2050.6   756.4  < 2e-16 ***\n## sex           1     42    42.3    15.6 8.89e-05 ***\n## Residuals   520   1410     2.7                     \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nm2 <- aov(data = d, femur_length ~ sex + age)\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##              Df Sum Sq Mean Sq F value  Pr(>F)    \n## sex           1     28    28.3   10.45 0.00131 ** \n## age           3   6166  2055.3  758.13 < 2e-16 ***\n## Residuals   520   1410     2.7                    \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nm1 <- lm(data = d, femur_length ~ age + sex)\nsummary(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = femur_length ~ age + sex, data = d)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -5.2429 -1.1040  0.1011  1.0560  5.3403 \n## \n## Coefficients:\n##             Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)   7.4340     0.1358   54.72  < 2e-16 ***\n## ageJ          2.3549     0.1779   13.24  < 2e-16 ***\n## ageS          6.0089     0.2019   29.77  < 2e-16 ***\n## ageA          9.7556     0.2232   43.71  < 2e-16 ***\n## sexmale       0.5701     0.1443    3.95 8.89e-05 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 1.647 on 520 degrees of freedom\n## Multiple R-squared:  0.8146,\tAdjusted R-squared:  0.8132 \n## F-statistic: 571.2 on 4 and 520 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nm2 <- lm(data = d, femur_length ~ sex + age)\nsummary(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = femur_length ~ sex + age, data = d)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -5.2429 -1.1040  0.1011  1.0560  5.3403 \n## \n## Coefficients:\n##             Estimate Std. Error t value Pr(>|t|)    \n## (Intercept)   7.4340     0.1358   54.72  < 2e-16 ***\n## sexmale       0.5701     0.1443    3.95 8.89e-05 ***\n## ageJ          2.3549     0.1779   13.24  < 2e-16 ***\n## ageS          6.0089     0.2019   29.77  < 2e-16 ***\n## ageA          9.7556     0.2232   43.71  < 2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 1.647 on 520 degrees of freedom\n## Multiple R-squared:  0.8146,\tAdjusted R-squared:  0.8132 \n## F-statistic: 571.2 on 4 and 520 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nWhy is this? In the first model, we are looking at the variance *within each age group* that is *explained by gender* while in the second case we are looking at the variance *within each gender* that is *explained by age*... but we have different numbers of observations in our different groups. This is known as an unbalanced design.\n\nWe can see the unbalanced design by tabulating the cases for each combination of factors.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntable(d$sex, d$age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##         \n##            I   J   S   A\n##   female 103  81  45  44\n##   male    97  69  55  31\n```\n\n\n:::\n:::\n\n\nRecall that ANOVA is based on splitting up the sums of squares, so that for a model like:\n\n$$Y_{i,j,k} = \\mu + a_i + b_j + ab_{i,j} + \\epsilon_{i,j,k}$$\n\nThe sums of squares add up such that:\n\n$$SS_{total} = SS_a + SS_b + SS_{ab} + SS_{residual}$$\n\nBy default, the `aov()` function uses something called **Type I Sums of Squares** (also called \"sequential sum of squares\"), which gives greater emphasis to the first factor in the model, leaving only residual variation to the remaining factors. It should be used when you want to first control for one factor, leaving the others to explain only any remaining differences. In a **Type I** ANOVA, the sums of squares for the first term are calculated around the grand mean of our observations, but the next terms are calculated as residuals around the average of the grand mean and the first group mean. This sequential procedure means our results depend on which term shows up first. This can have a marked effect on the sums of squares calculated, and hence on p values, when using an unbalanced design.\n\nBy contrast, what are know as **Type II** and **Type III Sums of Squares** both calculate the deviations between the individual observations within each group from the grand mean rather than the group mean.\n\n**Type II Sum of Squares** compares the main effects of each factor, assuming that the interaction between factors is minimal. Generally it is a much more appropriate test for comparing among different main effects and is more appropriate for us to use when there is an unbalanced design.\n\n**Type III Sum of Squares** (or \"marginal sum of squares\") is most appropriate when there is a significant interaction effect between factors. Since both **Type II** and **Type III** ANOVA calculate sums of squares around the grand mean, these are unaffected by different sample sizes across different categorical groups and do not arbitrarily give preference to one effect over another.\n\nTo summarize:\n\n- When our data are balanced, our factors are orthogonal, and all three types of sums of squares give the same results.\n- If our data are strongly unbalanced, we should generally be using Type II or Type III Sums of Squares, since we are generally interested in exploring the significance of one factor while controlling for the level of the other factors.\n- In general, if there is no significant interaction effect between factors, then Type II is more powerful than Type III.\n- If an important interaction is present, then Type II analysis is inappropriate, while Type III analysis can still be used, but the results need to be interpreted with caution (in the presence of interactions, individual main effects of different factors difficult to interpret).\n\nSee [this post](http://md.psych.bio.uni-goettingen.de/mv/unit/lm_cat/lm_cat_unbal_ss_explained.html) or [this post](http://goanna.cs.rmit.edu.au/~fscholer/anova.php) for further treatments of the issue.\n\nWe can use the `Anova()` function in the {car} package to run ANOVA with Type II and Type III Sums of Squares. In the examples below, both linear models, where the order of factors are reversed, give the same results for Type II and Type III ANOVA, but not for Type I. The `Anova()` function takes as its argument a model object, e.g., the result from a call to either `lm()` or `aov()` and recalculates the appropriate sums of squares. Note how the effect sizes (partial $\\eta^2$ values) are slightly different depending on whether they are being calculated from Type I or Type II ANOVA objects.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(car)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n## Loading required package: carData\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n## \n## Attaching package: 'car'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n## The following object is masked from 'package:dplyr':\n## \n##     recode\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr}\n\n```\n## The following object is masked from 'package:purrr':\n## \n##     some\n```\n\n\n:::\n\n```{.r .cell-code}\nm1 <- aov(data = d, femur_length ~ age + sex)\neffectsize(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # Effect Size for ANOVA (Type I)\n## \n## Parameter | Eta2 (partial) |       95% CI\n## -----------------------------------------\n## age       |           0.81 | [0.79, 1.00]\n## sex       |           0.03 | [0.01, 1.00]\n## \n## - One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\nm1 <- Anova(m1, type = \"II\")\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Anova Table (Type II tests)\n## \n## Response: femur_length\n##           Sum Sq  Df F value    Pr(>F)    \n## age       6165.8   3 758.126 < 2.2e-16 ***\n## sex         42.3   1  15.604 8.888e-05 ***\n## Residuals 1409.7 520                      \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nm2 <- aov(data = d, femur_length ~ sex + age)\neffectsize(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # Effect Size for ANOVA (Type I)\n## \n## Parameter | Eta2 (partial) |       95% CI\n## -----------------------------------------\n## sex       |           0.02 | [0.00, 1.00]\n## age       |           0.81 | [0.79, 1.00]\n## \n## - One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\nm2 <- Anova(m2, type = \"II\")\nm2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Anova Table (Type II tests)\n## \n## Response: femur_length\n##           Sum Sq  Df F value    Pr(>F)    \n## sex         42.3   1  15.604 8.888e-05 ***\n## age       6165.8   3 758.126 < 2.2e-16 ***\n## Residuals 1409.7 520                      \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize(m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # Effect Size for ANOVA (Type II)\n## \n## Parameter | Eta2 (partial) |       95% CI\n## -----------------------------------------\n## age       |           0.81 | [0.79, 1.00]\n## sex       |           0.03 | [0.01, 1.00]\n## \n## - One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\neffectsize(m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # Effect Size for ANOVA (Type II)\n## \n## Parameter | Eta2 (partial) |       95% CI\n## -----------------------------------------\n## sex       |           0.03 | [0.01, 1.00]\n## age       |           0.81 | [0.79, 1.00]\n## \n## - One-sided CIs: upper bound fixed at [1.00].\n```\n\n\n:::\n\n```{.r .cell-code}\nm1 <- aov(data = d, femur_length ~ age * sex)\nm1 <- Anova(m1, type = \"III\")\nm1\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Anova Table (Type III tests)\n## \n## Response: femur_length\n##             Sum Sq  Df   F value    Pr(>F)    \n## (Intercept) 6306.8   1 2510.7404 < 2.2e-16 ***\n## age         2661.3   3  353.1582 < 2.2e-16 ***\n## sex            2.8   1    1.1103    0.2925    \n## age:sex      111.0   3   14.7348  3.21e-09 ***\n## Residuals   1298.7 517                        \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nm2 <- aov(data = d, femur_length ~ sex * age)\nm2 <- Anova(m2, type = \"III\")\nm2\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Anova Table (Type III tests)\n## \n## Response: femur_length\n##             Sum Sq  Df   F value    Pr(>F)    \n## (Intercept) 6306.8   1 2510.7404 < 2.2e-16 ***\n## sex            2.8   1    1.1103    0.2925    \n## age         2661.3   3  353.1582 < 2.2e-16 ***\n## sex:age      111.0   3   14.7348  3.21e-09 ***\n## Residuals   1298.7 517                        \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\ndetach(package:car)\n```\n:::\n\n\n## Chi-Square Tests\n\nOne additional type of categorical data we will often encounter are counts of observations that fall into two or more categories (when we were dealing with $Z$ tests for proportion data, we were interested in something similar, though with two categories only). We can use **Chi-Square tests** to evaluate statistically the distribution of observations across levels of one or more categorical variables. To use the Chi-Square test we first derive a **Chi-Square** **statistic** ($\\chi^2$) , which is calculated as...\n\n$$\\chi^2 = \\displaystyle\\sum_{i=1}^k \\frac{(O_i - E_i)^2}{E_i}$$\n\nwhere:\n\n- $O_i$ = number of observations in the $i$th category\n- $E_i$ = number of observations in the $i$th category\n\nWe then compare the value of the $\\chi^2$ statistic to the Chi-Square distribution with $k-1$ degrees of freedom. The Chi-Square distribution, like the $F$ distribution, is a continuous probability distribution, defined for $x≥0$. It is governed by a single parameter, $df$.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npar(mfrow = c(1, 1))\ncurve(dchisq(x, df = 1),\n  col = \"green\", lty = 3, lwd = 2, xlim = c(0, 20),\n  main = \"Some Example Chi-Square Distributions\",\n  sub = \"(vertical line shows critical value for df=3)\",\n  ylab = \"f(x)\", xlab = \"x\"\n)\ncurve(dchisq(x, df = 3), col = \"blue\", lty = 3, lwd = 2, add = TRUE)\ncurve(dchisq(x, df = 5), col = \"red\", lty = 3, lwd = 2, add = TRUE)\ncurve(dchisq(x, df = 10), col = \"purple\", lty = 3, lwd = 2, add = TRUE)\nlegend(\"right\", c(\"df=1\", \"df=3\", \"df=5\", \"df=10\"),\n  lty = c(3, 3, 3, 3), lwd = 2,\n  col = c(\"green\", \"blue\", \"red\", \"purple\", \"black\"),\n  bty = \"n\", cex = .75\n)\n\ncrit <- qchisq(p = 0.95, df = 3)\ncrit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 7.814728\n```\n\n\n:::\n\n```{.r .cell-code}\nabline(v = crit)\nabline(h = 0)\npolygon(\n  cbind(\n    c(crit, seq(from = crit, to = 20, length.out = 1000), 8),\n    c(0, dchisq(seq(from = crit, to = 20, length.out = 1000), df = 3), 0)\n  ),\n  border = \"black\", col = rgb(0, 0, 1, 0.5)\n)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-42-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n### CHALLENGE {.unnumbered}\n\nLet's return to the zombie apocalypse survivors dataset, where we defined an occupation based on major for survivors of the zombie apocalypse. Use a Chi-Square test to evaluate the hypothesis that survivors of the zombie apocalypse are more likely than expected by chance to be natural science majors. Assume that assume our null hypothesis is that the proportions of different post-apocalypse occupations are equivalent, i.e., that $\\pi_{natural science}$ = $\\pi_{engineering}$= $\\pi_{logistics}$ = $\\pi_{other}$ = 0.25.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\n(obs.table <- table(z$occupation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{.details summary=\"Show Output\"}\n## \n## natural science     engineering       logistics           other \n##             390              98             218             294\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\n# returns the same as summary()\n(exp.table <- rep(0.25 * length(z$occupation), 4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{.details summary=\"Show Output\"}\n## [1] 250 250 250 250\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\n# equal expectation for each of 4 categories\noccupation.matrix <-\n  data.frame(cbind(\n    obs.table, exp.table,\n    (obs.table - exp.table)^2 / exp.table\n  ))\nnames(occupation.matrix) <- c(\"Oi\", \"Ei\", \"(Oi-Ei)^2/Ei\")\noccupation.matrix\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{.details summary=\"Show Output\"}\n##                  Oi  Ei (Oi-Ei)^2/Ei\n## natural science 390 250       78.400\n## engineering      98 250       92.416\n## logistics       218 250        4.096\n## other           294 250        7.744\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\n(X2 <- sum(occupation.matrix[, 3]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{.details summary=\"Show Output\"}\n## [1] 182.656\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"Show Code\"}\n(p <- 1 - pchisq(q = X2, length(obs.table) - 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```{.details summary=\"Show Output\"}\n## [1] 0\n```\n\n\n:::\n:::\n\n\nHere, we reject the null hypothesis that the proportions of different occupations among the survivors of the zombie apocalypse is equivalent.\n\nWe can do all this with a 1-liner in ***R***, too.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchisq.test(x = obs.table, p = c(0.25, 0.25, 0.25, 0.25))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tChi-squared test for given probabilities\n## \n## data:  obs.table\n## X-squared = 182.66, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\n# here p is a vector of expected proportions... default is uniform\nchisq.test(x = obs.table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tChi-squared test for given probabilities\n## \n## data:  obs.table\n## X-squared = 182.66, df = 3, p-value < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nchisq.test(x = obs.table, p = c(0.42, 0.07, 0.22, 0.29))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tChi-squared test for given probabilities\n## \n## data:  obs.table\n## X-squared = 13.416, df = 3, p-value = 0.003818\n```\n\n\n:::\n\n```{.r .cell-code}\n# with a different set of expected proportions... fail to reject H0\n```\n:::\n\n\nThe above was a **Chi-Square goodness of fit** test for one categorical variable... what about if we have two categorical variables and we are curious if there is an association among them? Then we do a **Chi-Square test of independence**. In this case, our Chi-Square statistic would be the sum of $\\frac{(O-E)^2}{E}$ across all cells in our table, and our degrees of freedom is (number of rows - 1) $\\times$ (number of columns - 1). Let's suppose we want to see if there is a relationship among zombie apocalypse survivors between gender and occupation.\n\nFirst, we determine our table of observed proportions:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(obs.table <- table(z$gender, z$occupation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##         \n##          natural science engineering logistics other\n##   Male               198          49       109   150\n##   Female             192          49       109   144\n```\n\n\n:::\n:::\n\n\nWe can view our data graphically using the `mosaic plot()` function.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmosaicplot(t(obs.table),\n  main = \"Contingency Table\",\n  col = c(\"darkseagreen\", \"gray\")\n)\n```\n\n::: {.cell-output-display}\n![](20-module_files/figure-html/unnamed-chunk-46-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n# the `t()` function transposes the table\n```\n:::\n\n\nThen, we determine our table of expected proportions:\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(r <- rowSums(obs.table)) # row margins\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##   Male Female \n##    506    494\n```\n\n\n:::\n\n```{.r .cell-code}\n(c <- colSums(obs.table)) # column margins\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## natural science     engineering       logistics           other \n##             390              98             218             294\n```\n\n\n:::\n\n```{.r .cell-code}\n(nr <- nrow(obs.table)) # row dimensions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 2\n```\n\n\n:::\n\n```{.r .cell-code}\n(nc <- ncol(obs.table)) # column dimensions\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 4\n```\n\n\n:::\n\n```{.r .cell-code}\n(exp.table <- matrix(rep(c, each = nr) * r / sum(obs.table),\n  nrow = nr,\n  ncol = nc,\n  dimnames = dimnames(obs.table),\n  byrow = FALSE\n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##         \n##          natural science engineering logistics   other\n##   Male            197.34      49.588   110.308 148.764\n##   Female          192.66      48.412   107.692 145.236\n```\n\n\n:::\n\n```{.r .cell-code}\n# calculates the product of c*r and divides by total\n(X2 <- sum((obs.table - exp.table)^2 / exp.table))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.07076686\n```\n\n\n:::\n\n```{.r .cell-code}\n(p <- 1 - pchisq(q = X2, df = (nr - 1) * (nc - 1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.9950981\n```\n\n\n:::\n:::\n\n\nAgain, we can do a one-liner for a test of independence...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nchisq.test(x = obs.table)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## \tPearson's Chi-squared test\n## \n## data:  obs.table\n## X-squared = 0.070767, df = 3, p-value = 0.9951\n```\n\n\n:::\n:::\n\n\n\n\n---\n\n## Concept Review {.unnumbered}\n\n- ANOVA is conceptually equivalent linear regression, but with one or more categorical predictor variables\n- ANOVA effectively tests whether the means of different groups are different\n- The Kruskall-Wallis test is a nonparametric alternative to a One-Way ANOVA that relaxes the need for normality in the distribution of data in each group and tests for a difference in the **medians** of different groups\n- ANOVAs should have balanced or roughly balanced numbers of observations within each categorical group\n- Chi-Square ($\\chi^2$) goodness-of-fit tests are another type of factor-based categorical data analysis, where we compare between observed and expected counts of observations in different grouping categories for either a single variable or two variables\n",
    "supporting": [
      "20-module_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}