{
  "hash": "25b85ab0be6bff634d210a2bc26a0f22",
  "result": {
    "engine": "knitr",
    "markdown": "# Generalized Linear Models {#module-23}\n\n## Objectives\n\n> In this module, we extend our discussion of regression modeling to include generalized linear models.\n\n## Preliminaries\n\n- Install and load this package in ***R***: [{lmtest}](https://cran.r-project.org/web/packages/lmtest/lmtest.pdf)\n- Load {tidyverse} and {broom}\n\n\n\n\n\n## Extending the \"General\" Model\n\nSo far, our discussion of regression has centered on standard or \"general\" linear models that assume that our response variables are continuously distributed and have normally distributed error terms (residuals) from our fitted models and that these error terms show constant variance across the range of our predictor variables. If these assumptions of general linear regression are not met, we can sometimes transform our variables to meet them, but other times we cannot, e.g., when we have binary or count data for a response variable.\n\nIn these cases, however, we can use a different regression technique called **generalized linear modeling** instead of general linear modeling. Generalized linear models, then, extend traditional regression models to allow the expected value of our response variable to depend on our predictor variable(s) through what is called a **link function**. It allows the response variable to belong to any of a set of distributions belonging to the \"exponential\" family (e.g., normal, Poisson, binomial), and it does not that require errors (model residuals) be normally distributed. It also does not require homogeneity of variance across the range of predictor variable values and allows for overdispersion (when the observed variance is larger than what the model assumes).\n\nOne of the most important differences is that in generalized linear modeling we no longer use ordinary least squares to estimate parameter values, but rather use maximum likelihood or Bayesian approaches.\n\nA generalized linear model consists of three components:\n\n- The **systematic or linear component**, which reflects the linear combination of predictor variables in our model. As in general linear regression, these can be be continuous and/or categorical. Interactions between predictors and polynomial functions of predictors can also be included, as in general linear modeling. [Recall that \"linear\" simply means the regression model is based on linear combinations of regression coefficients, not of variables.]\n\n- The **error structure** or **random component**, which refers to the probability distribution of residuals in the response variable after the linear component has been removed. The probability distribution of the residuals in a GLM must be from the exponential family of probability distributions, which includes the *normal* (Gaussian), *Poisson* (e.g., if our response variable consists of count data), *binomial* (e.g., if our response variable is binary, like \"yes/no\", \"presence/absence\"), *gamma*, *negative binomial*, etc.\n\n- A **link function**, which links the expected (mean) value of the response variable to the predictors. You can think of this as a transformation function. In GLM, as in general linear modeling, our linear component yields a predicted value, but this value is not the predicted value of our response variable, $Y$, *per se*. Rather, the predicted value from the regression model needs to be transformed back into a predicted $Y$ by applying the inverse of the link function.\n\n> **NOTE:** Using a particular link function is not the same as transforming the response variable. With the link function, we are modeling **some function of the expectation of the response variable** for given values of the predictor variables, but not the value of the response itself. Link functions typically transform the constrained scale of the expected values of a categorical response variable (such as a probability bounded by 0 and 1, or a mean count that has to be non-negative) to a continuous scale that is unbounded and that can thus be examined using regression. Predicted responses from a GLM (and the associated regression coefficients) typically need to be back-transformed to put them into the more intuitive scale of the original response variable.\n\nCommon link functions include:\n\n- The **identity link**, which is used to model $\\mu$, the mean value of $Y$ and is what we use implicitly in standard linear models. That is, our standard (or general) linear regression model is a particular case of the generalized linear model.\n- The **log link**, which is typically used to model **log(**$\\lambda$), the log of the mean value of $Y$. This link function is typically used for modeling for count data and is often referred to as “Poisson” or “log-linear” regression.\n- The **logit link**, which is **log(**$\\pi$/(1-$\\pi$)), is typically used for modeling binary data, and is often referred to as \"logistic\" regression. Here, the response is the log of the odds for a binary response.\n\n| Model      | Error Structure | Canonical Link Function |\n|------------|-----------------|-------------------------|\n| linear     | Gaussian        | identity                |\n| log linear | Poisson         | log                     |\n| logistic   | binomial        | logit                   |\n| gamma      | Gamma           | reciprocal (inverse)    |\n\nStandard or \"general\" linear regression can be viewed as a special case of GLM, where the random component of our model has a *normal distribution* and the link function is the *identity link* such that we are modeling an expected (mean) value for $Y$.\n\n## Model Fitting in GLM\n\nModel fitting and parameter estimation in GLM is commonly done using a maximum likelihood approach, which is an iterative process. To determine the fit of a given model, a GLM evaluates a linear predictor for each value of the response variable with a particular set of parameter values (i.e., $\\beta$ coefficients), then back-transforms the predicted value into the scale of the $Y$ variable using the inverse of the link function. These predicted values are compared with the observed values of $Y$. The parameters are then adjusted, and the model is refitted on the transformed scale in an iterative procedure until the fit stops improving and a best set of parameter values has been estimated. In ML approaches, then, the data are taken as a given, and we are trying to find the most likely combination of parameter values, under the given model, to fit those data. We judge the fit of the particular model of the basis of **how likely the data would be if the model were correct.**\n\nThe measure of discrepancy used in a GLM to assess the goodness of fit of the model to the data is called the **deviance**, which we can think of as analogous to the variance in a general linear model. Deviance is defined as **2** $\\times$ (the log-likelihood of a \"fully saturated\" model minus the log-likelihood of the proposed model). The former is a model that fits the data perfectly. Its likelihood is 1 and its log-likelihood is thus 0, so deviance functionally can be calculated as **-2** $\\times$ log-likelihood of the proposed model. Because the saturated model does not depend on any estimated parameters and has a likelihood of 1, *minimizing the deviance* for a particular model is the same as *maximizing the likelihood*. [For the ML process of parameter estimation, it is actually mathematically easier to maximize the log-likelihood, **ln(L)**, than it is to maximize the likelihood, **L**, so computationally that is what is usually done.] In generalized linear regression, the sum of squared \"deviance residuals\" of all the data points is analogous to the sum of squares of the residuals in a standard linear regression (i.e., this is what variation in the expectation of the response that the model does not explain).\n\nThe `glm()` function in ***R*** can be used for many types of generalized linear modeling, using a similar formula notation to that we've used before, with an additional argument, `family=`, to specify the kind of error structure we expect in the response variable (\"gaussian\", \"poisson\", \"binomial\", etc.): `glm(y ~ x, family = \"gaussian\")`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf <- \"https://raw.githubusercontent.com/difiore/ada-datasets/main/zombies.csv\"\nz <- read_csv(f, col_names = TRUE)\nglm <- glm(data = z, height ~ weight + age, family = \"gaussian\")\nsummary(glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = height ~ weight + age, family = \"gaussian\", data = z)\n## \n## Coefficients:\n##              Estimate Std. Error t value Pr(>|t|)    \n## (Intercept) 31.763388   0.470797   67.47   <2e-16 ***\n## weight       0.163107   0.002976   54.80   <2e-16 ***\n## age          0.618270   0.018471   33.47   <2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for gaussian family taken to be 2.689027)\n## \n##     Null deviance: 18559  on 999  degrees of freedom\n## Residual deviance:  2681  on 997  degrees of freedom\n## AIC: 3832.1\n## \n## Number of Fisher Scoring iterations: 2\n```\n\n\n:::\n:::\n\n\n> **NOTE:** This `glm()` with `family=\"gaussian\"` is equivalent to running a standard `lm()`...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm <- lm(data = z, height ~ weight + age)\nsummary(lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## lm(formula = height ~ weight + age, data = z)\n## \n## Residuals:\n##     Min      1Q  Median      3Q     Max \n## -5.2278 -1.1782 -0.0574  1.1566  5.4117 \n## \n## Coefficients:\n##              Estimate Std. Error t value Pr(>|t|)    \n## (Intercept) 31.763388   0.470797   67.47   <2e-16 ***\n## weight       0.163107   0.002976   54.80   <2e-16 ***\n## age          0.618270   0.018471   33.47   <2e-16 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## Residual standard error: 1.64 on 997 degrees of freedom\n## Multiple R-squared:  0.8555,\tAdjusted R-squared:  0.8553 \n## F-statistic:  2952 on 2 and 997 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAs with previous models, our explanatory variable, $X$, can be continuous (leading to a regression analysis) or categorical (leading to an ANOVA-like procedure called an *analysis of deviance*) or both.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nz$gender <- factor(z$gender)\nglm <- glm(data = z, height ~ weight + gender, family = \"gaussian\")\nsummary(glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = height ~ weight + gender, family = \"gaussian\", \n##     data = z)\n## \n## Coefficients:\n##              Estimate Std. Error t value Pr(>|t|)    \n## (Intercept) 40.714398   0.627933  64.839  < 2e-16 ***\n## weight       0.183945   0.004575  40.206  < 2e-16 ***\n## genderMale   0.878857   0.168299   5.222 2.15e-07 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for gaussian family taken to be 5.558875)\n## \n##     Null deviance: 18558.6  on 999  degrees of freedom\n## Residual deviance:  5542.2  on 997  degrees of freedom\n## AIC: 4558.3\n## \n## Number of Fisher Scoring iterations: 2\n```\n\n\n:::\n:::\n\n\n## Common Types of GLMs\n\nWe will explore two types of GLMs... **logistic regression** (used when our response variable is binary) and **log-linear or Poisson regression** (used when our response variable is count data).\n\n### Logistic Regression {.unnumbered}\n\nAs alluded to above, when we have a binary response variable (i.e., a categorical variable with two levels, 0 or 1), we actually are interested in modeling $\\pi_i$, which is the *probability that* $Y$ equals 1 for a given value of $X$ ($x_i$), rather than $\\mu_i$, the *mean value of* $Y$ for a given $X$, which is what we typically model with general linear regression. The usual model we fit to such data is the logistic regression model, which is a nonlinear model with a sigmoidal shape. The errors or residuals from such a model are not normally distributed but rather have a binomial distribution.\n\nWhen we do our regression, we actually use as our response variable the natural log of the **odds** between our two possible outcomes, i.e., the ratio of the probabilities that $y_i$ = 1 versus that $y_i$ = 0 for a given $x_i$, a ratio which we call the *logit*:\n\n$$g_i = logit(\\pi_i) = \\ln[\\frac{\\pi_i}{(1-\\pi_i)}] = \\beta_0 + \\beta_1x_i$$\n\nwhere $\\pi_i$ = the probability that $y_i$ equals 1 for a given value of $x_i$ and $(1-\\pi)$ = the probability that $y_i$ equals 0.\n\nThe *logit* transformation, then, is the link function connecting $Y$ to our predictors. The logit is useful as it converts probabilities, which lie in the range 0 to 1, into the scale of the whole real number line.\n\nWe can convert back from the *natural log of the odds* to an actual odds using the inverse of the *logit*, which is called the *expit*:\n\n$$expit(g_i) = \\frac{e^{g_i}}{1+e^{g_i}} = \\frac{1}{1+e^{-g_i}}=\\pi_i$$\n\n### EXAMPLE: {.unnumbered}\n\nSuppose we are interested in how a students' GRE scores, grade point averages (GPA), and ranking of their undergraduate institution (into quartiles, 1 to 4, from high to low), affect admission into graduate school. The response variable, \"admitted/not admitted\", is a binary variable, scored as 1/0.\n\nLoad in the \"graddata.csv\" dataset, which comes from [this website](https://stats.idre.ucla.edu/other/dae/), and then explore it using `head()`, `summary()`, `plot()`, `pairs()`, and `table()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf <- \"https://raw.githubusercontent.com/difiore/ada-datasets/main/graddata.csv\"\n# or f <- \"https://stats.idre.ucla.edu/stat/data/binary.csv\"\nd <- read_csv(f, col_names = TRUE)\nd$rank <- factor(d$rank, levels = c(1, 2, 3, 4))\n```\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nhead(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 4\n##   admit   gre   gpa rank \n##   <dbl> <dbl> <dbl> <fct>\n## 1     0   380  3.61 3    \n## 2     1   660  3.67 3    \n## 3     1   800  4    1    \n## 4     1   640  3.19 4    \n## 5     0   520  2.93 4    \n## 6     1   760  3    2\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nsummary(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##      admit             gre             gpa        rank   \n##  Min.   :0.0000   Min.   :220.0   Min.   :2.260   1: 61  \n##  1st Qu.:0.0000   1st Qu.:520.0   1st Qu.:3.130   2:151  \n##  Median :0.0000   Median :580.0   Median :3.395   3:121  \n##  Mean   :0.3175   Mean   :587.7   Mean   :3.390   4: 67  \n##  3rd Qu.:1.0000   3rd Qu.:660.0   3rd Qu.:3.670          \n##  Max.   :1.0000   Max.   :800.0   Max.   :4.000\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# first, some exploratory visualization\np <- ggplot(data = d, aes(x = gpa, y = admit)) +\n  geom_point(color = \"green\") +\n  xlab(\"GPA\") +\n  ylab(\"Admit\") +\n  ggtitle(\"Pr(Y) versus GPA\")\nq <- ggplot(data = d, aes(x = gpa, y = admit)) +\n  geom_point(color = \"blue\") +\n  xlab(\"GRE\") +\n  ylab(\"Admit\") +\n  ggtitle(\"Pr(Y) versus GRE\")\nlibrary(cowplot)\nplot_grid(p, q, nrow = 1)\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ndetach(package:cowplot)\npairs(d)\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-6-2.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n(t <- group_by(d, admit, rank) |>\n  summarize(n = n()) |>\n  pivot_wider(names_from = rank, values_from = n))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 2 × 5\n## # Groups:   admit [2]\n##   admit   `1`   `2`   `3`   `4`\n##   <dbl> <int> <int> <int> <int>\n## 1     0    28    97    93    55\n## 2     1    33    54    28    12\n```\n\n\n:::\n:::\n\n\nTo use logistic regression to look at how the *odds of admission* is influenced by *GRE scores*, we can call the `glm()` function with a model where **admit** is our response variable and **gre** is our predictor variable.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# glm of admit ~ gre\nglm <- glm(data = d, admit ~ gre, family = \"binomial\")\nsummary(glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = admit ~ gre, family = \"binomial\", data = d)\n## \n## Coefficients:\n##              Estimate Std. Error z value Pr(>|z|)    \n## (Intercept) -2.901344   0.606038  -4.787 1.69e-06 ***\n## gre          0.003582   0.000986   3.633  0.00028 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for binomial family taken to be 1)\n## \n##     Null deviance: 499.98  on 399  degrees of freedom\n## Residual deviance: 486.06  on 398  degrees of freedom\n## AIC: 490.06\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nHere is the equation representing the results of our model: $$logit(\\pi_i) = -2.901344 + 0.003582 \\times {gre}$$\n\n#### Interpretation and Hypothesis Testing {.unnumbered}\n\nWhen we get a $\\beta_1$ estimate from a logistic regression, it represents the *change in the log(odds)* of the **outcome** for an increase in one unit of our predictor variable, $X$.\n\nLooking at the coefficient for **gre**, we see it is positive and, while low, it is significantly different from 0. Thus, increasing GRE score results in an increase in the log(odds) of admission (i.e., students with higher scores are more likely to be admitted). Here, for every one unit change in **gre**, the log odds of admission (versus non-admission) increases by 0.003582.\n\nUsing the `predict()` function, we can plot our data and fit the change in the admitted/not admitted ratio across the range of GRE scores.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nx <- seq(from = 200, to = 800, by = 1)\nlog_odds <- predict(glm, newdata = data.frame(gre = x))\n# this function will predict the log(odds)...\n# running the `exp()` function, i.e., `exp(log_odds)` will yield the actual odds!\nodds <- exp(log_odds)\n\n# if we add the argument `type=\"response\"`, the `predict()` function will return the expected response on the scale of the Y variable, i.e., Pr(Y)\ny <- predict(glm, newdata = data.frame(gre = x), type = \"response\")\n\n# plotting our original data and the model\nres <- tibble(\n  gre = x,\n  log_odds = log_odds,\n  odds = odds,\n  pr_admit = y\n)\nhead(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 4\n##     gre log_odds  odds pr_admit\n##   <dbl>    <dbl> <dbl>    <dbl>\n## 1   200    -2.18 0.112    0.101\n## 2   201    -2.18 0.113    0.101\n## 3   202    -2.18 0.113    0.102\n## 4   203    -2.17 0.114    0.102\n## 5   204    -2.17 0.114    0.102\n## 6   205    -2.17 0.115    0.103\n```\n\n\n:::\n\n```{.r .cell-code}\ntail(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 4\n##     gre log_odds  odds pr_admit\n##   <dbl>    <dbl> <dbl>    <dbl>\n## 1   795  -0.0535 0.948    0.487\n## 2   796  -0.0499 0.951    0.488\n## 3   797  -0.0463 0.955    0.488\n## 4   798  -0.0427 0.958    0.489\n## 5   799  -0.0392 0.962    0.490\n## 6   800  -0.0356 0.965    0.491\n```\n\n\n:::\n\n```{.r .cell-code}\np <- ggplot(data = d, aes(x = gre, y = admit)) +\n  geom_point(alpha = 0.5) +\n  xlab(\"GRE Score\") +\n  ylab(\"Pr(admit)\") +\n  ggtitle(\"Pr(admit) versus GRE Score\") +\n  geom_line(data = res, aes(x = gre, y = pr_admit))\np\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-8-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n# or\np <- ggplot(data = d, aes(x = gre, y = admit)) +\n  geom_point(alpha = 0.5) +\n  xlab(\"GRE Score\") +\n  ylab(\"Pr(admit)\") +\n  ggtitle(\"Pr(admit) versus GRE Score\") +\n  geom_smooth(method = \"glm\", method.args = list(family = binomial))\np\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-8-2.png){fig-align='center' width=672}\n:::\n:::\n\n\nBy exponentiating the regression coefficient, $\\beta_1$, we can get the actual odds change, as opposed to the log(odds) change, associated with a 1 unit change in GRE score.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(odds_change <- exp(glm$coefficients[2]))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##      gre \n## 1.003589\n```\n\n\n:::\n:::\n\n\nHere, a 1 unit increase in gre results in a 0.36% increase in the odds of admission.\n\nAs in simple (general) linear regression, the key null hypothesis, $H_0$, of relevance when fitting a simple logistic regression model is that our regression coefficient, $\\beta$, is zero, i.e. that there is no relationship between the binary response variable and the predictor variable.\n\nThere are two common ways to test this $H_0$. The first is to calculate the **Wald statistic** for the predictor variable and compare this to the standard normal or $z$ distribution. This is like a maximum likelihood-based version of a **t test**. The Wald statistic is, like a t statistic, our $\\beta$ parameter estimate divided by the standard error of that estimate: $\\frac{\\beta_1}{SE( \\beta_1)}$). This is most appropriate when sample sizes are large. The \"z value\" in the summary table for the model shows us the value of the Wald statistic.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsummary(glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = admit ~ gre, family = \"binomial\", data = d)\n## \n## Coefficients:\n##              Estimate Std. Error z value Pr(>|z|)    \n## (Intercept) -2.901344   0.606038  -4.787 1.69e-06 ***\n## gre          0.003582   0.000986   3.633  0.00028 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for binomial family taken to be 1)\n## \n##     Null deviance: 499.98  on 399  degrees of freedom\n## Residual deviance: 486.06  on 398  degrees of freedom\n## AIC: 490.06\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nIf we wanted to calculate the Wald statistic by hand, we can do so easily. Below, we use the convenient `tidy()` function from the {broom} package to pull out a table of results from our GLM very easily. Note that `tidy()` works on lots of different linear model objects, e.g., those created by `lm()` and `glm()` (though not `lmer()`).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(results <- tidy(glm))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 2 × 5\n##   term        estimate std.error statistic    p.value\n##   <chr>          <dbl>     <dbl>     <dbl>      <dbl>\n## 1 (Intercept) -2.90     0.606        -4.79 0.00000169\n## 2 gre          0.00358  0.000986      3.63 0.000280\n```\n\n\n:::\n\n```{.r .cell-code}\nresults$wald <- results$estimate / results$std.error\nresults$p <- 2 * (1 - pnorm(abs(results$wald)))\n# 2-tailed p value associated with the Wald statistic\nresults\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 2 × 7\n##   term        estimate std.error statistic    p.value  wald          p\n##   <chr>          <dbl>     <dbl>     <dbl>      <dbl> <dbl>      <dbl>\n## 1 (Intercept) -2.90     0.606        -4.79 0.00000169 -4.79 0.00000169\n## 2 gre          0.00358  0.000986      3.63 0.000280    3.63 0.000280\n```\n\n\n:::\n:::\n\n\nJust as when running an `lm()`, we can get the confidence intervals around our `glm()` model estimates several different ways. First, we can use the `confint()` function, giving our GLM model results as an argument, which yields a CI based on a maximum likelihood approach.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalpha <- 0.05\n(CI <- confint(glm, level = 1 - alpha))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##                    2.5 %       97.5 %\n## (Intercept) -4.119988259 -1.739756286\n## gre          0.001679963  0.005552748\n```\n\n\n:::\n\n```{.r .cell-code}\n# this function returns a CI based on log-likelihood, an iterative ML process\n```\n:::\n\n\nAlternatively, we can use the `confint.default()` function, which returns a CI based on standard errors, the way we have calculated them by hand previously.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(CI <- confint.default(glm, level = 1 - alpha))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##                    2.5 %       97.5 %\n## (Intercept) -4.089156159 -1.713532380\n## gre          0.001649677  0.005514746\n```\n\n\n:::\n\n```{.r .cell-code}\n# which is equivalent to how we have calculated CIs previously\n\nresults$lower <- results$estimate -\n  qnorm(1 - alpha / 2) * results$std.error\nresults$upper <- results$estimate +\n  qnorm(1 - alpha / 2) * results$std.error\n(CI <- results |> select(c(\"term\", \"lower\", \"upper\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 2 × 3\n##   term           lower    upper\n##   <chr>          <dbl>    <dbl>\n## 1 (Intercept) -4.09    -1.71   \n## 2 gre          0.00165  0.00551\n```\n\n\n:::\n:::\n\n\n### CHALLENGE {.unnumbered}\n\nRepeat the logistic regression above, but using **gpa** rather than **gre** as the predictor variable.\n\n- Is **gpa** a significant predictor of the odds of admission?\n- What is the estimate of $\\beta_1$ and the 95% CI around that estimate?\n- How much does an increase of 1 unit in **gpa** increase the actual *odds* (as opposed to the *log(odds)*) of admission?\n- What is the 95% CI around these odds?\n\n> **HINT:** For the latter two questions, you will need to apply the `exp()` function and convert the *log(odds)* into actual *odds*.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nglm <- glm(data = d, admit ~ gpa, family = \"binomial\")\nsummary(glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = admit ~ gpa, family = \"binomial\", data = d)\n## \n## Coefficients:\n##             Estimate Std. Error z value Pr(>|z|)    \n## (Intercept)  -4.3576     1.0353  -4.209 2.57e-05 ***\n## gpa           1.0511     0.2989   3.517 0.000437 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for binomial family taken to be 1)\n## \n##     Null deviance: 499.98  on 399  degrees of freedom\n## Residual deviance: 486.97  on 398  degrees of freedom\n## AIC: 490.97\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n(log_odds <- glm$coefficients) # pull out coefficients\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## (Intercept)         gpa \n##   -4.357587    1.051109\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n(CI <- confint(glm, level = 1 - alpha)) # calculate CIs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##                  2.5 %    97.5 %\n## (Intercept) -6.4334239 -2.367430\n## gpa          0.4742282  1.647959\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# exponentiate to convert to the odds scale instead of log(odds) scale\n(odds <- exp(log_odds))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## (Intercept)         gpa \n##  0.01280926  2.86082123\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n(CI_odds <- exp(CI)) # exponentiate to convert to odds scale\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##                   2.5 %     97.5 %\n## (Intercept) 0.001606939 0.09372126\n## gpa         1.606773662 5.19636490\n```\n\n\n:::\n:::\n\n\n- Graph the **probability of admission**, i.e., *Pr(admit)* or $\\pi_i$, for students with GPAs between 2.0 and 4.0 GPAs, superimposed on a point plot of admission (0 or 1) by **gpa**.\n\n> **HINT:** Use the `predict()` function with `type=\"response\"` to yield $\\pi_i$ directly.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nx <- seq(from = 2, to = 4, length.out = 100)\ny <- predict(glm, newdata = data.frame(gpa = x), type = \"response\")\n\nres <- tibble(\n  gpa = x,\n  pr_admit = y\n)\n\n# IMPORTANT: Using type=\"response\" returns predictions on the scale of the Y variable, in this case Pr(admit). Using the default for the `type=` argument would return a prediction on the logit scale, i.e., the log(odds), which equals log(Pr(admit)/(1-Pr(admit)))\nhead(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 2\n##     gpa pr_admit\n##   <dbl>    <dbl>\n## 1  2      0.0949\n## 2  2.02   0.0967\n## 3  2.04   0.0986\n## 4  2.06   0.101 \n## 5  2.08   0.102 \n## 6  2.10   0.104\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\np <- ggplot(data = d, aes(x = gpa, y = admit)) +\n  geom_point() +\n  xlab(\"GPA\") +\n  ylab(\"Pr(admit)\") +\n  ggtitle(\"Pr(admit) versus GPA\") +\n  geom_line(data = res, aes(x = gpa, y = pr_admit))\np\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-15-1.png){fig-align='center' width=384}\n:::\n:::\n\n\nThe `predict()` function can also be used to get confidence intervals around our estimate of the log(odds of admission) (if the `type=` argument is unspecified or set to \"link\"), or around the estimate of the probability of admission (if the `type=` argument is set to \"response\"), by using the argument `se.fit=TRUE`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalpha <- 0.05\ny <- predict(glm, newdata = data.frame(gpa = x), type = \"response\", se.fit = TRUE)\nres <- tibble(\n  gpa = x,\n  pr_admit = y$fit,\n  se = y$se.fit\n)\n\nres$lower <- res$pr_admit -\n  qnorm(1 - alpha / 2) * res$se\nres$upper <- res$pr_admit +\n  qnorm(1 - alpha / 2) * res$se\nhead(res)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 5\n##     gpa pr_admit     se  lower upper\n##   <dbl>    <dbl>  <dbl>  <dbl> <dbl>\n## 1  2      0.0949 0.0383 0.0199 0.170\n## 2  2.02   0.0967 0.0384 0.0215 0.172\n## 3  2.04   0.0986 0.0385 0.0231 0.174\n## 4  2.06   0.101  0.0387 0.0247 0.176\n## 5  2.08   0.102  0.0388 0.0264 0.178\n## 6  2.10   0.104  0.0389 0.0281 0.181\n```\n\n\n:::\n\n```{.r .cell-code}\n# plot...\n# note we start by plotting the model data (res) b/c we are hand-plotting the SE ribbon\np <- ggplot(data = res, aes(x = gpa, y = pr_admit)) +\n  geom_line() +\n  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2) +\n  # and then we add in points\n  geom_point(data = d, aes(x = gpa, y = admit), alpha = 0.5) +\n  xlab(\"GPA\") +\n  ylab(\"Pr(admit)\") +\n  ggtitle(\"Pr(admit) versus GPA\")\np\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-16-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\n# or, alternatively...\n# note here we start with plotting the raw data\np <- ggplot(data = d, aes(x = gpa, y = admit)) +\n  geom_point(alpha = 0.5) +\n  xlab(\"GPA\") +\n  ylab(\"Pr(admit)\") +\n  ggtitle(\"Pr(admit) versus GPA\") +\n  # and then add in the fitted line via glm\n  geom_smooth(method = \"glm\", method.args = list(family = binomial))\np\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-16-2.png){fig-align='center' width=672}\n:::\n:::\n\n\n#### Likelihood Ratio Tests {.unnumbered}\n\nTo evaluate the significance of an **overall model** in a logistic regression, we can compare the fit of a more complex model to that of a nested, reduced model, just as when we discussed model selection approaches for simple linear regression using **partial F tests**.\n\nFor example, to test the null hypothesis that $\\beta_1$ = 0 for a simple logistic regression model with a single predictor, we would compare the log-likelihood of the full model to that of the reduced, intercept-only model. This is called a **likelihood ratio test**. Likelihood ratio tests are very similar to partial F tests in that they compare the full model with a nested, reduced model where the explanatory variables of interest are omitted. However, instead of using a test statistic based on a ratio of *variances* explained by the two models and interpreting that by comparison to an $F$ distribution, we create a test statistic that is a ratio of the *log-likelihoods* of the two models and interpret that statistic by comparison to a $\\chi^2$ distribution with a given number of degrees of freedom. Still, the underlying idea is conceptually the same.\n\nA likelihood ratio test comparing a proposed model and a nested, reduced model can be performed using the `anova()` function where we specify the `test=` argument to be either `LRT` or `Chisq` (these are equivalent).\n\nRecall that when we used the `anova()` function to run F ratio tests to compare the proportion of **variance** explained by two general linear models, we specified that `test=\"F\" and generated an F statistic which was considered relative to an F distribution to calculate a p value.\n\nWith generalized linear models, because we are working with deviances and likelihood ratios, the test statistic we generate is *ratio of likelihoods* (which is equivalent to a difference in deviances, see below) rather than a *ratio of variances*. That statistic is then considered relative to a $\\chi^2$ distribution to determine the p value. The relevant degrees of freedom for the likelihood ratio test is the **\\# of parameters in the proposed model minus the \\# parameters in the nested model** (here, df = 2 - 1 = 1).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nproposed <- glm(data = d, admit ~ gpa, family = \"binomial\")\nreduced <- glm(data = d, admit ~ 1, family = \"binomial\")\nanova(reduced, proposed, test = \"LRT\") # or `test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Analysis of Deviance Table\n## \n## Model 1: admit ~ 1\n## Model 2: admit ~ gpa\n##   Resid. Df Resid. Dev Df Deviance Pr(>Chi)    \n## 1       399     499.98                         \n## 2       398     486.97  1   13.009  0.00031 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWith this low p value, we would reject the null hypothesis that removing the variable of interest (*gpa*) from our model does not result in a loss of fit. \n\nAlternatively, we could use the function `lrtest()` from the {lmtest} package to do the same likelihood ratio test of the two models.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlrtest(reduced, proposed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Likelihood ratio test\n## \n## Model 1: admit ~ 1\n## Model 2: admit ~ gpa\n##   #Df  LogLik Df  Chisq Pr(>Chisq)    \n## 1   1 -249.99                         \n## 2   2 -243.48  1 13.009    0.00031 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nWe can also perform a likelihood ratio test by hand by taking the difference between the *deviances* of the two models. The deviance for a generalized linear model is analogous to the the residual sum of squares (i.e., unexplained variance) in a general linear model -- i.e, lower deviance and lower RSS both mean better models. Deviance is calculated as a kind of \"distance\" of given model from a fully \"saturated\" model, i.e., a model where each data point has its own parameters. The likelihood of a fully \"saturated\" model is 1, thus its log-likelihood is log(1) = 0.\n\n- *Deviance* = 2 $\\times$ (log-likelihood of the saturated model - log-likelihood of the proposed model)\n- *Deviance* = 2 $\\times$ (0 - log-likelihood of the proposed model)\n- *Deviance* = -2 $\\times$ (log-likelihood of the proposed model)\n\nWe can get the deviance associated with a given glm model object by accessing its `$deviance` slot or by using the `deviance()` function with the model object as an argument.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# deviance of intercept only model\n(D_reduced <- reduced$deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 499.9765\n```\n\n\n:::\n\n```{.r .cell-code}\n# or...\n(D_reduced <- deviance(reduced))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 499.9765\n```\n\n\n:::\n\n```{.r .cell-code}\n# deviance of proposed model with intercept and one predictor\n(D_proposed <- proposed$deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 486.9676\n```\n\n\n:::\n\n```{.r .cell-code}\n# or...\n(D_proposed <- deviance(proposed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 486.9676\n```\n\n\n:::\n:::\n\n\nThe $\\chi^2$ statistic is then just the difference of the deviances...\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(x2 <- D_reduced - D_proposed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 13.0089\n```\n\n\n:::\n\n```{.r .cell-code}\n# this is a measure of how much the fit improves by adding in the predictor\n(p <- 1 - pchisq(x2, df = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.0003100148\n```\n\n\n:::\n\n```{.r .cell-code}\n# or\n(p <- pchisq(x2, df = 1, lower.tail = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.0003100148\n```\n\n\n:::\n\n```{.r .cell-code}\n# df = difference in number of parameters in the proposed versus reduced models\n```\n:::\n\n\nThe `$null.deviance` slot of a model object returns, for any model, the deviance associated with an intercept only null model.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(x2 <- reduced$null.deviance - reduced$deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 5.115908e-12\n```\n\n\n:::\n\n```{.r .cell-code}\n# this is essentially 0 because here the `reduced` model is the intercept only model!\n(p <- pchisq(q = 0, df = 0, lower.tail = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 1\n```\n\n\n:::\n\n```{.r .cell-code}\n(x2 <- proposed$null.deviance - proposed$deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 13.0089\n```\n\n\n:::\n\n```{.r .cell-code}\n(p <- pchisq(q = x2, df = 1, lower.tail = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.0003100148\n```\n\n\n:::\n\n```{.r .cell-code}\n# df = difference in number of parameters in the proposed versus reduced model\n```\n:::\n\n\nHere is some additional useful information about interpreting the results of `summary()` from running a logistic regression based on [this post from *StackExchange*](http://stats.stackexchange.com/questions/108995/interpreting-residual-and-null-deviance-in-glm-r) and [this post from *The Analysis Factor*](http://www.theanalysisfactor.com/r-glm-model-fit/)\n\n> Let $n$ = the number of observations in the data set and $K$ = the number of predictor terms in a proposed model.\n>\n> - The *Saturated Model* is a model that assumes each data point has its own parameter, which means we have $n$ parameters to describe the data\n>\n> - The *Null Model* is a model that assumes exactly the opposite, i.e., one parameter describes all of the data points, which means only 1 parameter, the intercept, is estimated from the data\n>\n> - The *Proposed Model* is the model we are fitting by GLM, which has $K$ parameters terms (1 for the intercept, plus 1 for each predictor variable/interaction term)\n>\n> - *Null Deviance* = deviance of the Null Model, calculated as *2(log-likelihood of the Saturated Model* $-$ log-likelihood of a Null Model), where df = $n$ - 1\n>\n> - *Residual Deviance* = *2(log-likelihood of the saturated model* $-$ log-likelihood of the proposed model), where df = $n$ - $K$\n>\n> If the null deviance is really small, it means that the *Null Model* explains the data pretty well. Likewise, if the residual deviance is really small, then the *Proposed Model* explains the data pretty well.\n>\n> If you want to compare a *Proposed Model* against a *Null*, or intercept-only model, then you can look at *Null Deviance* $-$ *Residual Deviance* for that model, which yields a difference that can be examined against a $\\chi^2$ distribution with $K$ degrees of freedom.\n>\n> If you want to compare one *Proposed Model* against a nested *Reduced Model*, then you can look at *Residual Deviance for the Reduced Model* $-$ *Residual Deviance for the Proposed Model*, which again yields a difference that can be examined against a $\\chi^2$ distribution with df = ($K$ for Proposed Model) - ($K$ for Reduced Model).\n>\n> This deviance-based, $\\chi^2$-like statistic is also referred to as a **G Square** or **G** statistic. If the p value associated with this statistic is less than the alpha level, it means that the the fuller model is associated with significantly reduced deviance relative to the nested reduced model, and thus has a better fit. We would thus reject the null hypothesis that the fuller model is not better than the reduced one.\n\n#### Multiple Logistic Regression {.unnumbered}\n\nLogistic regression can be easily extended to situations with multiple predictor variables, including both continuous and categorical variables, as in our discussion of multiple regression under the general linear model.\n\n### CHALLENGE {.unnumbered}\n\nUsing the same \"graddata.csv\" dataset, run a multiple logistic regression analysis using *gpa*, *gre*, and *rank* to look at student admissions to graduate school. Do not, at first, include any interaction terms.\n\n- What variables are significant predictors of the log(odds ratio) of admission?\n- What is the value of the log(odds ratio) coefficient and the 95% CIs around that value for the two continuous variable (*gpa* and *gre*), when taking the effects of the other and of rank into account? What do these translate into on the actual odds ratio scale?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# model with 3 predictors\nglmGGR <- glm(data = d, formula = admit ~ gpa + gre + rank, family = binomial)\nsummary(glmGGR)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = admit ~ gpa + gre + rank, family = binomial, data = d)\n## \n## Coefficients:\n##              Estimate Std. Error z value Pr(>|z|)    \n## (Intercept) -3.989979   1.139951  -3.500 0.000465 ***\n## gpa          0.804038   0.331819   2.423 0.015388 *  \n## gre          0.002264   0.001094   2.070 0.038465 *  \n## rank2       -0.675443   0.316490  -2.134 0.032829 *  \n## rank3       -1.340204   0.345306  -3.881 0.000104 ***\n## rank4       -1.551464   0.417832  -3.713 0.000205 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for binomial family taken to be 1)\n## \n##     Null deviance: 499.98  on 399  degrees of freedom\n## Residual deviance: 458.52  on 394  degrees of freedom\n## AIC: 470.52\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\nlog_coeff <- glmGGR$coefficients # extract coefficients...\nlog_coeff_CI <- confint(glmGGR, level = 1 - alpha)\n# and calculate 95% CIs around them\n(results <- cbind(log_coeff, log_coeff_CI)) # none include 0!\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##                log_coeff         2.5 %       97.5 %\n## (Intercept) -3.989979073 -6.2716202334 -1.792547080\n## gpa          0.804037549  0.1602959439  1.464142727\n## gre          0.002264426  0.0001375921  0.004435874\n## rank2       -0.675442928 -1.3008888002 -0.056745722\n## rank3       -1.340203916 -2.0276713127 -0.670372346\n## rank4       -1.551463677 -2.4000265384 -0.753542605\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\n# convert results out of log scale\ncoeff <- exp(log_coeff) # convert results out of log scale\ncoeff_CI <- exp(log_coeff_CI)\n(results <- cbind(coeff, coeff_CI))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##                 coeff       2.5 %    97.5 %\n## (Intercept) 0.0185001 0.001889165 0.1665354\n## gpa         2.2345448 1.173858216 4.3238349\n## gre         1.0022670 1.000137602 1.0044457\n## rank2       0.5089310 0.272289674 0.9448343\n## rank3       0.2617923 0.131641717 0.5115181\n## rank4       0.2119375 0.090715546 0.4706961\n```\n\n\n:::\n:::\n\n\n- Is the model including all three predictors better than models that include just two predictors?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# compare each 2 predictor model to 3 predictor model\nglmGG <- glm(data = d, formula = admit ~ gpa + gre, family = binomial)\nglmGR <- glm(data = d, formula = admit ~ gpa + rank, family = binomial)\nglmRG <- glm(data = d, formula = admit ~ gre + rank, family = binomial)\nlrtest(glmGG, glmGGR) # or anova(glmGG, glmGGR, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Likelihood ratio test\n## \n## Model 1: admit ~ gpa + gre\n## Model 2: admit ~ gpa + gre + rank\n##   #Df  LogLik Df  Chisq Pr(>Chisq)    \n## 1   3 -240.17                         \n## 2   6 -229.26  3 21.826  7.088e-05 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nlrtest(glmGR, glmGGR) # or anova(glmGR, glmGGR, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Likelihood ratio test\n## \n## Model 1: admit ~ gpa + rank\n## Model 2: admit ~ gpa + gre + rank\n##   #Df  LogLik Df  Chisq Pr(>Chisq)  \n## 1   5 -231.44                       \n## 2   6 -229.26  1 4.3578    0.03684 *\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\nlrtest(glmRG, glmGGR) # or anova(glmRG, glmGGR, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Likelihood ratio test\n## \n## Model 1: admit ~ gre + rank\n## Model 2: admit ~ gpa + gre + rank\n##   #Df  LogLik Df  Chisq Pr(>Chisq)  \n## 1   5 -232.27                       \n## 2   6 -229.26  1 6.0143    0.01419 *\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n> The 3-predictor model is indeed better and any of the 2-predictor models!\n\n- Compare a model that includes the three predictors with no interactions to one that includes the three predictors and all possible interactions.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# compare model with and model without interactions\nglmGGR_no <- glm(data = d, admit ~ rank + gpa + gre, family = \"binomial\")\nglmGGR_all <- glm(data = d, admit ~ rank * gpa * gre, family = \"binomial\")\nlrtest(glmGGR_no, glmGGR_all)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Likelihood ratio test\n## \n## Model 1: admit ~ rank + gpa + gre\n## Model 2: admit ~ rank * gpa * gre\n##   #Df  LogLik Df  Chisq Pr(>Chisq)\n## 1   6 -229.26                     \n## 2  16 -225.19 10 8.1317      0.616\n```\n\n\n:::\n\n```{.r .cell-code}\n# or anova(glmGGR_no, glmGGR_all, test=\"Chisq\")\n```\n:::\n\n\n> Adding interaction terms to the 3-predictor model does not significantly decrease the deviance!\n\n### Log-Linear or Poisson Regression {.unnumbered}\n\nSometimes, we want to model a response variable that is in the form of count data (e.g., species richness on an island in terms of distance from the mainland, number of plants of a particular species found in a sampling plot in relation to altitude). Many discrete response variables have counts as possible outcomes. Binomial counts are the number of successes $x$ in a fixed number of trials, $n$. Poisson counts are the number occurrences of some event in a certain interval of time (or space). While binomial counts only take values between 0 and n, Poisson counts have no upper bound. We are going to focus on Poisson counts here.\n\nAs we have discussed before, for Poisson-distributed variables, the mean and the variance are equal and represented by a single parameter ($\\lambda$), which is the expectation for both the mean ($\\mu_i$) and the variance. Since the variance is proportional to the mean (and Poisson residuals are not homoskedastistic), using standard linear models based on normal distributions may not be appropriate.\n\nWe have seen that sometimes we can simply transform a response variable with some kind of power transformation to make it appear more normally distributed, but an alternative is to use a GLM with a Poisson error term and use a *log* transformation as the link function, resulting in in a **log-linear** model. Thus, when we do Poisson regression, our regression model tries to predict the natural log of the expected value of $Y$, i.e., $\\mu_i$ (or $\\lambda_i$).\n\n> **NOTE:** Remember, the ***R*** function `log()`, by default, refers to the natural log.\n\nThe link function is thus...\n\n$$g_i=\\ln(\\mu_i) = \\beta_0 + \\beta_1x_i$$\n\n... and the inverse link function is...\n\n$$e^{g_i} = \\mu_i\\ (i.e.,\\ \\lambda_i)$$\n\nOur regression model formulation is the same as in logistic regression, above, except we use `family=\"Poisson\"`, i.e, `glm(y ~ x, family = \"poisson\")`\n\n### EXAMPLE: {.unnumbered}\n\nResearchers studied the reproductive success of a set of male woolly monkeys over a period of 8 years. The age of each monkey at the beginning of the study and the number of successful matings they had during the 8 years were recorded, and they were also scored into ranks of \"high\", \"medium\", and \"low\". We assume the number of matings follows a Poisson distribution, and we are interested in exploring whether mating success depends on the age of the monkey in question.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nf <- \"https://raw.githubusercontent.com/difiore/ada-datasets/main/woollydata.csv\"\nd <- read_csv(f, col_names = TRUE)\nhead(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 4\n##   name    success   age rank  \n##   <chr>     <dbl> <dbl> <chr> \n## 1 Aaron        15  9.8  medium\n## 2 Adam         14 12.1  medium\n## 3 Agustin      22 16.3  high  \n## 4 Alan          9  8.79 low   \n## 5 Andrew       12  6.81 low   \n## 6 Anthony      11 14.8  low\n```\n\n\n:::\n\n```{.r .cell-code}\nd$name <- factor(d$name)\nd$rank <- factor(d$rank, levels = c(\"low\", \"medium\", \"high\"))\nsummary(d)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##       name       success           age             rank   \n##  James  : 2   Min.   : 5.00   Min.   : 5.740   low   :24  \n##  Aaron  : 1   1st Qu.: 9.00   1st Qu.: 9.555   medium:12  \n##  Adam   : 1   Median :12.00   Median :10.765   high  :24  \n##  Agustin: 1   Mean   :12.12   Mean   :10.884              \n##  Alan   : 1   3rd Qu.:14.00   3rd Qu.:12.285              \n##  Andrew : 1   Max.   :24.00   Max.   :16.330              \n##  (Other):53\n```\n\n\n:::\n\n```{.r .cell-code}\n# first, some exploratory visualization\n(p <- ggplot(data = d, aes(x = age, y = success)) +\n  geom_point()\n  +\n  xlab(\"Age\") +\n  ylab(\"Mating Success\"))\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\npairs(d)\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-25-2.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\ntable(d$rank, d$success)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##         \n##          5 6 7 8 9 10 11 12 13 14 15 16 17 19 20 21 22 24\n##   low    0 1 1 4 4  2  2  5  2  1  1  0  1  0  0  0  0  0\n##   medium 0 0 0 0 1  1  2  1  1  2  1  0  0  1  1  1  0  0\n##   high   1 1 1 1 3  1  2  3  2  2  2  1  1  1  0  0  1  1\n```\n\n\n:::\n\n```{.r .cell-code}\n# glm of success ~ age\nglm <- glm(data = d, success ~ age, family = \"poisson\")\nsummary(glm)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = success ~ age, family = \"poisson\", data = d)\n## \n## Coefficients:\n##             Estimate Std. Error z value Pr(>|z|)    \n## (Intercept)  1.84007    0.17696  10.398  < 2e-16 ***\n## age          0.05920    0.01541   3.841 0.000122 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for poisson family taken to be 1)\n## \n##     Null deviance: 75.972  on 59  degrees of freedom\n## Residual deviance: 61.179  on 58  degrees of freedom\n## AIC: 322.88\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n:::\n\n\nIn the `summary()`, note that the residual deviance is slighly higher than the residual degrees of freedom, which suggests that our data are slightly overdispersed (i.e., there is some extra, unexplained variation in the response, where the variance is greater than the mean). If this were dramatic, we might use \"quasipoisson\" for the family instead, but we will stick with \"poisson\".\n\nWe can generate a nice summary table of results with `tidy()`, and by setting `conf.int = TRUE` we use an ML approach to estimate the CI.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(results <- tidy(glm, conf.int = TRUE, conf.level = 0.95))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 2 × 7\n##   term        estimate std.error statistic  p.value conf.low conf.high\n##   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n## 1 (Intercept)   1.84      0.177      10.4  2.52e-25   1.49      2.18  \n## 2 age           0.0592    0.0154      3.84 1.22e- 4   0.0290    0.0894\n```\n\n\n:::\n:::\n\n\nNow, let's fit a \"line\" of best fit through our data, along with 95% CI around this \"line\". We want to plot the relationship between **success**, rather than **log(success)**, and **age**, so this relationship will not actually be linear but log-linear.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nalpha <- 0.05\nx <- data.frame(age = seq(from = 5, to = 17, by = 1))\nprediction <- cbind(age = x, predict(glm, newdata = x, type = \"response\", se.fit = TRUE))\n# IMPORTANT: Using the argument `type=\"response\"` makes our prediction be in units of our actual Y variable, success, rather than log(success)\nprediction$lower <- prediction$fit - qnorm(1 - alpha / 2) * prediction$se.fit\nprediction$upper <- prediction$fit + qnorm(1 - alpha / 2) * prediction$se.fit\nhead(prediction)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n##   age       fit    se.fit residual.scale     lower    upper\n## 1   5  8.465986 0.8711054              1  6.758651 10.17332\n## 2   6  8.982273 0.7966819              1  7.420806 10.54374\n## 3   7  9.530046 0.7145099              1  8.129632 10.93046\n## 4   8 10.111223 0.6274232              1  8.881497 11.34095\n## 5   9 10.727844 0.5422279              1  9.665096 11.79059\n## 6  10 11.382067 0.4739422              1 10.453158 12.31098\n```\n\n\n:::\n\n```{.r .cell-code}\np <- p + geom_line(data = prediction, aes(x = age, y = fit)) +\n  geom_ribbon(data = prediction, aes(\n    x = age, y = fit,\n    ymin = lower, ymax = upper\n  ), alpha = 0.2)\np # note the curvilinear \"line\" of best fit\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-27-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nIs this model better than an intercept-only model? YES!\n\nWe can see this by doing a likelihood ratio test.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nproposed <- glm(data = d, success ~ age, family = \"poisson\")\nreduced <- glm(data = d, success ~ 1, family = \"poisson\")\n# using the `lrtest()` function\nlrtest(reduced, proposed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Likelihood ratio test\n## \n## Model 1: success ~ 1\n## Model 2: success ~ age\n##   #Df  LogLik Df  Chisq Pr(>Chisq)    \n## 1   1 -166.84                         \n## 2   2 -159.44  1 14.794  0.0001199 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# or, by using the `anova()` function\nanova(reduced, proposed, test = \"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## Analysis of Deviance Table\n## \n## Model 1: success ~ 1\n## Model 2: success ~ age\n##   Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n## 1        59     75.972                          \n## 2        58     61.179  1   14.794 0.0001199 ***\n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n\n```{.r .cell-code}\n# or, based on the deviance difference between the reduced and proposed models\n(x2 <- reduced$deviance - proposed$deviance)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 14.79362\n```\n\n\n:::\n\n```{.r .cell-code}\n(p <- 1 - pchisq(x2, df = 1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## [1] 0.0001199407\n```\n\n\n:::\n\n```{.r .cell-code}\n# or, calculating the model deviances by hand using the `logLik()` function (which returns the log-likelihood of the model) and then taking the difference in deviance\n(D_reduced <- -2 * logLik(reduced))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## 'log Lik.' 333.6736 (df=1)\n```\n\n\n:::\n\n```{.r .cell-code}\n(D_proposed <- -2 * logLik(proposed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## 'log Lik.' 318.8799 (df=2)\n```\n\n\n:::\n\n```{.r .cell-code}\n(x2 <- D_reduced - D_proposed)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## 'log Lik.' 14.79362 (df=1)\n```\n\n\n:::\n\n```{.r .cell-code}\n(p <- pchisq(x2, df = 1, lower.tail = FALSE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## 'log Lik.' 0.0001199407 (df=1)\n```\n\n\n:::\n\n```{.r .cell-code}\n# df = difference in # of parameters in the proposed versus reduced model\n```\n:::\n\n\nAs mentioned in [**Module 22**](#module-22), the Akaike Information Criterion, or AIC, is another way of evaluating and comparing related models. For similar models, those with lower AIC models are preferred over those with higher AIC. The AIC value is based on the deviance associated with the model, but it penalizes model complexity. Much like an adjusted $R^2$, its intent is to prevent you from including irrelevant predictors when choosing among similar models. Models with low AICs represent a better fit to the data, and if many models have similarly low AICs, you should choose the one with the fewest model terms. For both continuous and categorical predictors, we prefer comparing full and reduced models against one another to test individual terms rather than comparing the fit of all possible models and trying and select a single \"best\" one. Thus, AIC values are useful for comparing models, but they are not interpretable on their own. The `logLik()` function returns the log-likelihood associated with a particular model and can be used to calculate AIC values by hand.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n(AICproposed <- 2 * 2 - 2 * logLik(proposed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## 'log Lik.' 322.8799 (df=2)\n```\n\n\n:::\n\n```{.r .cell-code}\n# AIC = (2 * # parameters estimated() minus (2 * log-likelihood of model)\n# for the proposed model, we estimated 2 parameters\n(AICreduced <- 2 * 1 - 2 * logLik(reduced))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## 'log Lik.' 335.6736 (df=1)\n```\n\n\n:::\n\n```{.r .cell-code}\n# for the reduced model, we estimated 1 parameter\n```\n:::\n\n\nHere, the log-likelihood of the model including *age* as a predictor is much lower than the log-likelihood of the reduced (intercept only) model, so we prefer the former.\n\n### CHALLENGE {.unnumbered}\n\nUsing the woolly monkey mating success data set, explore multiple Poisson regression models of [a] mating success in relation to *rank* and [b] mating success in relation to *age* + *rank*, and [c] mating success in relation to *age* + *rank* + their interaction on your own. What conclusions can you come to about the importance of rank and rank in combination with age versus age alone?\n\n#### Mating Success in Relation to Rank {.unnumbered}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# glm of success ~ rank\nglm1 <- glm(data = d, success ~ rank, family = \"poisson\")\nsummary(glm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = success ~ rank, family = \"poisson\", data = d)\n## \n## Coefficients:\n##             Estimate Std. Error z value Pr(>|z|)    \n## (Intercept)  2.36321    0.06262  37.737   <2e-16 ***\n## rankmedium   0.28178    0.09919   2.841   0.0045 ** \n## rankhigh     0.17247    0.08498   2.029   0.0424 *  \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for poisson family taken to be 1)\n## \n##     Null deviance: 75.972  on 59  degrees of freedom\n## Residual deviance: 67.229  on 57  degrees of freedom\n## AIC: 330.93\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ntidy(glm1, conf.int = TRUE, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 3 × 7\n##   term        estimate std.error statistic   p.value conf.low conf.high\n##   <chr>          <dbl>     <dbl>     <dbl>     <dbl>    <dbl>     <dbl>\n## 1 (Intercept)    2.36     0.0626     37.7  1.21e-311  2.24        2.48 \n## 2 rankmedium     0.282    0.0992      2.84 4.50e-  3  0.0859      0.475\n## 3 rankhigh       0.172    0.0850      2.03 4.24e-  2  0.00621     0.340\n```\n\n\n:::\n:::\n\n\n#### Mating Success in Relation to Age + Rank {.unnumbered}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# glm of success~age+rank\nglm2 <- glm(data = d, success ~ age + rank, family = \"poisson\")\nsummary(glm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = success ~ age + rank, family = \"poisson\", data = d)\n## \n## Coefficients:\n##             Estimate Std. Error z value Pr(>|z|)    \n## (Intercept)  1.71566    0.18490   9.279  < 2e-16 ***\n## age          0.05848    0.01547   3.780 0.000157 ***\n## rankmedium   0.26400    0.09930   2.659 0.007844 ** \n## rankhigh     0.18419    0.08504   2.166 0.030324 *  \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for poisson family taken to be 1)\n## \n##     Null deviance: 75.972  on 59  degrees of freedom\n## Residual deviance: 52.905  on 56  degrees of freedom\n## AIC: 318.61\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ntidy(glm2, conf.int = TRUE, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 4 × 7\n##   term        estimate std.error statistic  p.value conf.low conf.high\n##   <chr>          <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n## 1 (Intercept)   1.72      0.185       9.28 1.71e-20   1.35      2.08  \n## 2 age           0.0585    0.0155      3.78 1.57e- 4   0.0282    0.0888\n## 3 rankmedium    0.264     0.0993      2.66 7.84e- 3   0.0679    0.457 \n## 4 rankhigh      0.184     0.0850      2.17 3.03e- 2   0.0178    0.351\n```\n\n\n:::\n:::\n\n\n#### Mating Success in Relation to Age + Rank + Their Interaction {.unnumbered}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\n# glm of success ~ age + rank + age:rank\nglm3 <- glm(data = d, success ~ age * rank, family = \"poisson\")\nsummary(glm3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## \n## Call:\n## glm(formula = success ~ age * rank, family = \"poisson\", data = d)\n## \n## Coefficients:\n##                Estimate Std. Error z value Pr(>|z|)    \n## (Intercept)     2.03352    0.29131   6.981 2.94e-12 ***\n## age             0.03000    0.02568   1.168    0.243    \n## rankmedium     -0.16033    0.48228  -0.332    0.740    \n## rankhigh       -0.35253    0.39958  -0.882    0.378    \n## age:rankmedium  0.03768    0.04141   0.910    0.363    \n## age:rankhigh    0.04820    0.03514   1.372    0.170    \n## ---\n## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n## \n## (Dispersion parameter for poisson family taken to be 1)\n## \n##     Null deviance: 75.972  on 59  degrees of freedom\n## Residual deviance: 50.925  on 54  degrees of freedom\n## AIC: 320.63\n## \n## Number of Fisher Scoring iterations: 4\n```\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ntidy(glm3, conf.int = TRUE, conf.level = 0.95)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n## # A tibble: 6 × 7\n##   term           estimate std.error statistic  p.value conf.low conf.high\n##   <chr>             <dbl>     <dbl>     <dbl>    <dbl>    <dbl>     <dbl>\n## 1 (Intercept)      2.03      0.291      6.98  2.94e-12   1.45      2.60  \n## 2 age              0.0300    0.0257     1.17  2.43e- 1  -0.0202    0.0805\n## 3 rankmedium      -0.160     0.482     -0.332 7.40e- 1  -1.11      0.779 \n## 4 rankhigh        -0.353     0.400     -0.882 3.78e- 1  -1.13      0.433 \n## 5 age:rankmedium   0.0377    0.0414     0.910 3.63e- 1  -0.0433    0.119 \n## 6 age:rankhigh     0.0482    0.0351     1.37  1.70e- 1  -0.0208    0.117\n```\n\n\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(sjPlot)\nlibrary(effects)\nplot_model(glm3, type = \"eff\", term = \"age\") +\n  geom_point(data = d, aes(x = age, y = success))\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-33-1.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\nplot_model(glm3, type = \"eff\", term = \"rank\")\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-33-2.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\nplot(predictorEffects(glm3, partial.residuals = TRUE))\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-33-3.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\nplot(allEffects(glm3, partial.residuals = TRUE))\n```\n\n::: {.cell-output-display}\n![](23-module_files/figure-html/unnamed-chunk-33-4.png){fig-align='center' width=672}\n:::\n\n```{.r .cell-code}\ndetach(package:sjPlot)\ndetach(package:effects)\n```\n:::\n\n\n\n\n---\n\n## Concept Review {.unnumbered}\n\n- Generalized linear modeling extends general linear modeling to accommodate response variables that are not continuously distributed (e.g., binary responses, count data, proportion data)\n- What is being predicted in generalized linear model is some function of the expected value of an observed response, not the observed response *per se*\n    - The link/inverse link function is what connects the response predicted by the GLM back to the scale of the original observed response\n- For binary response variables, we use **logistic** regression, where the response variable is natural log of the **odds ratio** between two possible outcomes:\n\n$$\\ln[\\frac{\\pi_i}{(1-\\pi_i)}] = \\beta_0 + \\beta_1x_i$$\n\n- For response variables that are open-ended counts, we use **log-linear** or **Poisson regression**, where the response variable is the natural log of the expected value of the count\n\n$$\\lambda_i = \\beta_0 + \\beta_1x_i$$\n\n- As with simple (or general) linear models, we can create generalized linear models with more than one predictor variable, with a combination of continuous and categorial predictors, and with interactions between predictors\n",
    "supporting": [
      "23-module_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}